import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'bn';

interface Translations {
  [key: string]: {
    en: string;
    hi: string;
    bn: string;
  };
}

const translations: Translations = {
  // Navigation
  'nav.home': { en: 'Home', hi: 'होम', bn: 'হোম' },
  'nav.jobs': { en: 'Jobs', hi: 'नौकरियां', bn: 'চাকরি' },
  'nav.companies': { en: 'Companies', hi: 'कंपनियां', bn: 'কোম্পানি' },
  'nav.employers': { en: 'Employers', hi: 'नियोक्ता', bn: 'নিয়োগকর্তা' },
  'nav.candidates': { en: 'Candidates', hi: 'उम्मीदवार', bn: 'প্রার্থী' },
  'nav.resources': { en: 'Resources', hi: 'संसाधन', bn: 'রিসোর্স' },
  'nav.tools': { en: 'Tools', hi: 'उपकरण', bn: 'টুলস' },
  'nav.blog': { en: 'Blog', hi: 'ब्लॉग', bn: 'ব্লগ' },
  'nav.helpCenter': { en: 'Help Center', hi: 'सहायता केंद्र', bn: 'সহায়তা কেন্দ্র' },
  'nav.login': { en: 'Login', hi: 'लॉगिन', bn: 'লগইন' },
  'nav.signup': { en: 'Sign Up', hi: 'साइन अप', bn: 'সাইন আপ' },
  'nav.dashboard': { en: 'Dashboard', hi: 'डैशबोर्ड', bn: 'ড্যাশবোর্ড' },
  'nav.profile': { en: 'Profile', hi: 'प्रोफ़ाइल', bn: 'প্রোফাইল' },
  'nav.logout': { en: 'Logout', hi: 'लॉगआउट', bn: 'লগআউট' },
  'nav.settings': { en: 'Settings', hi: 'सेटिंग्स', bn: 'সেটিংস' },
  'nav.employerLogin': { en: 'Employer Login', hi: 'नियोक्ता लॉगिन', bn: 'নিয়োগকর্তা লগইন' },
  'nav.candidateLogin': { en: 'Candidate Login', hi: 'उम्मीदवार लॉगिन', bn: 'প্রার্থী লগইন' },
  'nav.new': { en: 'New', hi: 'नया', bn: 'নতুন' },
  'nav.aiResumeBuilder': { en: 'AI Resume Builder', hi: 'AI रिज्यूमे बिल्डर', bn: 'AI রেজুমে বিল্ডার' },
  'nav.aiResumeChecker': { en: 'AI Resume Checker', hi: 'AI रिज्यूमे चेकर', bn: 'AI রেজুমে চেকার' },
  'nav.polls': { en: 'Polls', hi: 'पोल', bn: 'পোল' },
  'nav.contestsSurveys': { en: 'Contests & Paid Surveys', hi: 'प्रतियोगिताएं और सर्वे', bn: 'প্রতিযোগিতা ও সার্ভে' },
  'nav.byLocation': { en: 'By Location', hi: 'स्थान के अनुसार', bn: 'অবস্থান অনুসারে' },
  'nav.byIndustry': { en: 'By Industry', hi: 'उद्योग के अनुसार', bn: 'শিল্প অনুসারে' },
  'nav.byExperience': { en: 'By Experience', hi: 'अनुभव के अनुसार', bn: 'অভিজ্ঞতা অনুসারে' },
  'nav.byType': { en: 'By Type', hi: 'प्रकार के अनुसार', bn: 'ধরন অনুসারে' },
  'nav.viewAllJobs': { en: 'View All Jobs', hi: 'सभी नौकरियां देखें', bn: 'সমস্ত চাকরি দেখুন' },

  // Hero Section
  'hero.title': { en: 'Find Your Dream Job', hi: 'अपनी सपनों की नौकरी खोजें', bn: 'আপনার স্বপ্নের চাকরি খুঁজুন' },
  'hero.subtitle': { en: 'Discover thousands of job opportunities with AI-powered matching', hi: 'AI-संचालित मिलान के साथ हज़ारों नौकरी के अवसर खोजें', bn: 'AI-চালিত ম্যাচিং সহ হাজার হাজার চাকরির সুযোগ আবিষ্কার করুন' },
  'hero.search': { en: 'Search jobs...', hi: 'नौकरियाँ खोजें...', bn: 'চাকরি খুঁজুন...' },
  'hero.location': { en: 'Location', hi: 'स्थान', bn: 'অবস্থান' },
  'hero.find': { en: 'Find Jobs', hi: 'नौकरियाँ खोजें', bn: 'চাকরি খুঁজুন' },
  'hero.findDreamCareer': { en: 'Find Your Dream Career', hi: 'अपना सपनों का करियर खोजें', bn: 'আপনার স্বপ্নের ক্যারিয়ার খুঁজুন' },
  'hero.aiPowered': { en: 'AI-Powered Job Matching', hi: 'AI-संचालित जॉब मिलान', bn: 'AI-চালিত চাকরি ম্যাচিং' },
  'hero.popular': { en: 'Popular:', hi: 'लोकप्रिय:', bn: 'জনপ্রিয়:' },

  // Stats
  'stats.activeJobs': { en: 'Active Jobs', hi: 'सक्रिय नौकरियाँ', bn: 'সক্রিয় চাকরি' },
  'stats.companies': { en: 'Companies', hi: 'कंपनियाँ', bn: 'কোম্পানি' },
  'stats.jobSeekers': { en: 'Job Seekers', hi: 'नौकरी खोजने वाले', bn: 'চাকরি প্রার্থী' },
  'stats.successRate': { en: 'Success Rate', hi: 'सफलता दर', bn: 'সাফল্যের হার' },

  // How It Works
  'howItWorks.title': { en: 'How It Works', hi: 'यह कैसे काम करता है', bn: 'এটি কীভাবে কাজ করে' },
  'howItWorks.subtitle': { en: 'Your journey to the perfect job is just a few simple steps away', hi: 'आपकी सही नौकरी की यात्रा बस कुछ आसान कदम दूर है', bn: 'নিখুঁত চাকরির দিকে আপনার যাত্রা মাত্র কয়েকটি সহজ ধাপ দূরে' },
  'howItWorks.step1.title': { en: 'Create Account', hi: 'खाता बनाएं', bn: 'অ্যাকাউন্ট তৈরি করুন' },
  'howItWorks.step1.desc': { en: 'Sign up in seconds and build your professional profile with your skills and experience.', hi: 'सेकंडों में साइन अप करें और अपने कौशल और अनुभव के साथ अपनी पेशेवर प्रोफ़ाइल बनाएं।', bn: 'কয়েক সেকেন্ডে সাইন আপ করুন এবং আপনার দক্ষতা এবং অভিজ্ঞতা দিয়ে পেশাদার প্রোফাইল তৈরি করুন।' },
  'howItWorks.step2.title': { en: 'Discover Jobs', hi: 'नौकरियाँ खोजें', bn: 'চাকরি আবিষ্কার করুন' },
  'howItWorks.step2.desc': { en: 'Browse thousands of jobs with smart filters. Our AI matches you with the best opportunities.', hi: 'स्मार्ट फिल्टर के साथ हज़ारों नौकरियाँ ब्राउज़ करें। हमारी AI आपको सर्वोत्तम अवसरों से मिलाती है।', bn: 'স্মার্ট ফিল্টার সহ হাজার হাজার চাকরি ব্রাউজ করুন। আমাদের AI আপনাকে সেরা সুযোগের সাথে মিলিয়ে দেয়।' },
  'howItWorks.step3.title': { en: 'Apply Easily', hi: 'आसानी से आवेदन करें', bn: 'সহজে আবেদন করুন' },
  'howItWorks.step3.desc': { en: 'Apply with one click using your profile. Track all your applications in one place.', hi: 'अपनी प्रोफ़ाइल का उपयोग करके एक क्लिक में आवेदन करें। अपने सभी आवेदनों को एक ही स्थान पर ट्रैक करें।', bn: 'আপনার প্রোফাইল ব্যবহার করে এক ক্লিকে আবেদন করুন। এক জায়গায় আপনার সমস্ত আবেদন ট্র্যাক করুন।' },
  'howItWorks.step4.title': { en: 'Get Hired', hi: 'नौकरी पाएं', bn: 'চাকরি পান' },
  'howItWorks.step4.desc': { en: 'Connect with employers, ace your interviews, and land your dream job.', hi: 'नियोक्ताओं से जुड़ें, अपने इंटरव्यू में सफल हों, और अपनी सपनों की नौकरी पाएं।', bn: 'নিয়োগকর্তাদের সাথে সংযুক্ত হন, ইন্টারভিউতে সফল হন এবং স্বপ্নের চাকরি পান।' },

  // CTA Section
  'cta.lookingForJob': { en: 'Looking for a Job?', hi: 'नौकरी की तलाश में?', bn: 'চাকরি খুঁজছেন?' },
  'cta.jobSeekerDesc': { en: 'Create your free profile, upload your resume, and let our AI match you with the perfect opportunities.', hi: 'अपनी मुफ्त प्रोफ़ाइल बनाएं, अपना रिज्यूमे अपलोड करें, और हमारी AI को आपके लिए सही अवसर खोजने दें।', bn: 'আপনার বিনামূল্যে প্রোফাইল তৈরি করুন, আপনার রিজিউম আপলোড করুন এবং আমাদের AI কে নিখুঁত সুযোগ খুঁজে দিতে দিন।' },
  'cta.getStartedFree': { en: 'Get Started Free', hi: 'मुफ्त में शुरू करें', bn: 'বিনামূল্যে শুরু করুন' },
  'cta.lookingToHire': { en: 'Looking to Hire?', hi: 'भर्ती करना चाहते हैं?', bn: 'নিয়োগ করতে চান?' },
  'cta.employerDesc': { en: 'Post your jobs, browse qualified candidates, and find the perfect match for your team.', hi: 'अपनी नौकरियाँ पोस्ट करें, योग्य उम्मीदवारों को ब्राउज़ करें, और अपनी टीम के लिए सही मैच खोजें।', bn: 'আপনার চাকরি পোস্ট করুন, যোগ্য প্রার্থীদের ব্রাউজ করুন এবং আপনার দলের জন্য নিখুঁত ম্যাচ খুঁজুন।' },
  'cta.postJob': { en: 'Post a Job', hi: 'नौकरी पोस्ट करें', bn: 'চাকরি পোস্ট করুন' },

  // Featured Jobs
  'featuredJobs.title': { en: 'Featured Jobs', hi: 'विशेष नौकरियाँ', bn: 'বৈশিষ্ট্যযুক্ত চাকরি' },
  'featuredJobs.subtitle': { en: 'Discover opportunities from top companies', hi: 'शीर्ष कंपनियों से अवसर खोजें', bn: 'শীর্ষ কোম্পানিগুলি থেকে সুযোগ আবিষ্কার করুন' },
  'featuredJobs.viewAll': { en: 'View All Jobs', hi: 'सभी नौकरियाँ देखें', bn: 'সমস্ত চাকরি দেখুন' },
  'featuredJobs.viewDetails': { en: 'View Details', hi: 'विवरण देखें', bn: 'বিস্তারিত দেখুন' },

  // Job Types
  'job.fullTime': { en: 'Full Time', hi: 'पूर्णकालिक', bn: 'পূর্ণ সময়' },
  'job.partTime': { en: 'Part Time', hi: 'अंशकालिक', bn: 'খণ্ডকালীন' },
  'job.contract': { en: 'Contract', hi: 'अनुबंध', bn: 'চুক্তি' },
  'job.internship': { en: 'Internship', hi: 'इंटर्नशिप', bn: 'ইন্টার্নশিপ' },
  'job.remote': { en: 'Remote', hi: 'रिमोट', bn: 'দূরবর্তী' },

  // Experience Levels
  'exp.fresher': { en: 'Fresher', hi: 'फ्रेशर', bn: 'নবাগত' },
  'exp.junior': { en: 'Junior', hi: 'जूनियर', bn: 'জুনিয়র' },
  'exp.mid': { en: 'Mid Level', hi: 'मध्य स्तर', bn: 'মাঝারি স্তর' },
  'exp.senior': { en: 'Senior', hi: 'सीनियर', bn: 'সিনিয়র' },
  'exp.lead': { en: 'Lead', hi: 'लीड', bn: 'লিড' },
  'exp.executive': { en: 'Executive', hi: 'एग्जीक्यूटिव', bn: 'এক্সিকিউটিভ' },

  // Common
  'common.apply': { en: 'Apply Now', hi: 'अभी आवेदन करें', bn: 'এখনই আবেদন করুন' },
  'common.save': { en: 'Save', hi: 'सेव करें', bn: 'সংরক্ষণ করুন' },
  'common.saved': { en: 'Saved', hi: 'सेव किया गया', bn: 'সংরক্ষিত' },
  'common.view': { en: 'View', hi: 'देखें', bn: 'দেখুন' },
  'common.edit': { en: 'Edit', hi: 'संपादित करें', bn: 'সম্পাদনা করুন' },
  'common.delete': { en: 'Delete', hi: 'हटाएं', bn: 'মুছুন' },
  'common.cancel': { en: 'Cancel', hi: 'रद्द करें', bn: 'বাতিল করুন' },
  'common.submit': { en: 'Submit', hi: 'जमा करें', bn: 'জমা দিন' },
  'common.loading': { en: 'Loading...', hi: 'लोड हो रहा है...', bn: 'লোড হচ্ছে...' },
  'common.noResults': { en: 'No results found', hi: 'कोई परिणाम नहीं मिला', bn: 'কোন ফলাফল পাওয়া যায়নি' },
  'common.search': { en: 'Search', hi: 'खोजें', bn: 'অনুসন্ধান' },
  'common.filter': { en: 'Filter', hi: 'फ़िल्टर', bn: 'ফিল্টার' },
  'common.sortBy': { en: 'Sort by', hi: 'इसके अनुसार क्रमबद्ध करें', bn: 'এই অনুসারে সাজান' },
  'common.clear': { en: 'Clear', hi: 'साफ़ करें', bn: 'পরিষ্কার করুন' },
  'common.clearFilters': { en: 'Clear Filters', hi: 'फ़िल्टर साफ़ करें', bn: 'ফিল্টার পরিষ্কার করুন' },
  'common.previous': { en: 'Previous', hi: 'पिछला', bn: 'পূর্ববর্তী' },
  'common.next': { en: 'Next', hi: 'अगला', bn: 'পরবর্তী' },
  'common.processing': { en: 'Processing', hi: 'प्रोसेसिंग', bn: 'প্রক্রিয়াকরণ' },
  'common.replace': { en: 'Replace', hi: 'बदलें', bn: 'প্রতিস্থাপন করুন' },
  'common.upload': { en: 'Upload', hi: 'अपलोड करें', bn: 'আপলোড করুন' },
  'common.download': { en: 'Download', hi: 'डाउनलोड करें', bn: 'ডাউনলোড করুন' },
  'common.more': { en: 'more', hi: 'और', bn: 'আরও' },

  // Auth
  'auth.email': { en: 'Email', hi: 'ईमेल', bn: 'ইমেল' },
  'auth.password': { en: 'Password', hi: 'पासवर्ड', bn: 'পাসওয়ার্ড' },
  'auth.fullName': { en: 'Full Name', hi: 'पूरा नाम', bn: 'পুরো নাম' },
  'auth.loginTitle': { en: 'Welcome Back', hi: 'वापस स्वागत है', bn: 'স্বাগতম' },
  'auth.welcomeEmployer': { en: 'Welcome Employer', hi: 'स्वागत नियोक्ता', bn: 'স্বাগতম নিয়োগকর্তা' },
  'auth.employerTagline': { en: 'Find the best talent for your team', hi: 'अपनी टीम के लिए सबसे अच्छी प्रतिभा खोजें', bn: 'আপনার দলের জন্য সেরা প্রতিভা খুঁজুন' },
  'auth.signupTitle': { en: 'Create Account', hi: 'खाता बनाएं', bn: 'অ্যাকাউন্ট তৈরি করুন' },
  'auth.jobSeeker': { en: 'Job Seeker', hi: 'नौकरी खोजने वाला', bn: 'চাকরি প্রার্থী' },
  'auth.employer': { en: 'Employer', hi: 'नियोक्ता', bn: 'নিয়োগকর্তা' },
  'auth.selectRole': { en: 'I am a', hi: 'मैं हूँ', bn: 'আমি একজন' },
  'auth.orContinueWith': { en: 'Or continue with', hi: 'या इसके साथ जारी रखें', bn: 'অথবা এর সাথে চালিয়ে যান' },
  'auth.alreadyHaveAccount': { en: 'Already have an account?', hi: 'पहले से खाता है?', bn: 'ইতিমধ্যে অ্যাকাউন্ট আছে?' },
  'auth.dontHaveAccount': { en: "Don't have an account?", hi: 'खाता नहीं है?', bn: 'অ্যাকাউন্ট নেই?' },
  'auth.forgotPassword': { en: 'Forgot Password?', hi: 'पासवर्ड भूल गए?', bn: 'পাসওয়ার্ড ভুলে গেছেন?' },
  'auth.createAccountBenefits': { en: 'Create an account to save jobs, track applications, and get personalized recommendations.', hi: 'नौकरियाँ सेव करने, आवेदनों को ट्रैक करने और व्यक्तिगत सिफारिशें प्राप्त करने के लिए खाता बनाएं।', bn: 'চাকরি সংরক্ষণ, আবেদন ট্র্যাক এবং ব্যক্তিগত সুপারিশ পেতে একটি অ্যাকাউন্ট তৈরি করুন।' },

  // Role Selection Modal
  'roleModal.welcomeTo': { en: 'Welcome to', hi: 'स्वागत है', bn: 'স্বাগতম' },
  'roleModal.brandName': { en: 'TrueJobs', hi: 'TrueJobs', bn: 'TrueJobs' },
  'roleModal.subtitle': { en: 'Tell us who you are to get started', hi: 'शुरू करने के लिए हमें बताएं कि आप कौन हैं', bn: 'শুরু করতে আমাদের বলুন আপনি কে' },
  'roleModal.imCandidate': { en: "I'm a Candidate", hi: 'मैं एक उम्मीदवार हूँ', bn: 'আমি একজন প্রার্থী' },
  'roleModal.candidateDesc': { en: 'Looking for job opportunities', hi: 'नौकरी के अवसर खोज रहा हूँ', bn: 'চাকরির সুযোগ খুঁজছি' },
  'roleModal.imEmployer': { en: "I'm an Employer", hi: 'मैं एक नियोक्ता हूँ', bn: 'আমি একজন নিয়োগকর্তা' },
  'roleModal.employerDesc': { en: 'Looking to hire talent', hi: 'प्रतिभा को नियुक्त करना चाहता हूँ', bn: 'প্রতিভা নিয়োগ করতে চাই' },
  'roleModal.skipText': { en: 'You can skip this and browse jobs without signing in', hi: 'आप इसे छोड़ सकते हैं और बिना साइन इन किए नौकरियाँ ब्राउज़ कर सकते हैं', bn: 'আপনি এটি এড়িয়ে যেতে পারেন এবং সাইন ইন না করে চাকরি ব্রাউজ করতে পারেন' },

  // Dashboard
  'dashboard.welcome': { en: 'Welcome', hi: 'स्वागत है', bn: 'স্বাগতম' },
  'dashboard.applications': { en: 'My Applications', hi: 'मेरे आवेदन', bn: 'আমার আবেদন' },
  'dashboard.savedJobs': { en: 'Saved Jobs', hi: 'सेव की गई नौकरियाँ', bn: 'সংরক্ষিত চাকরি' },
  'dashboard.recommendations': { en: 'Recommended Jobs', hi: 'अनुशंसित नौकरियाँ', bn: 'সুপারিশকৃত চাকরি' },

  // Employer
  'employer.postJob': { en: 'Post a Job', hi: 'नौकरी पोस्ट करें', bn: 'চাকরি পোস্ট করুন' },
  'employer.manageJobs': { en: 'Manage Jobs', hi: 'नौकरियाँ प्रबंधित करें', bn: 'চাকরি পরিচালনা করুন' },
  'employer.applicants': { en: 'Applicants', hi: 'आवेदक', bn: 'আবেদনকারী' },
  'employer.company': { en: 'Company Profile', hi: 'कंपनी प्रोफ़ाइल', bn: 'কোম্পানি প্রোফাইল' },

  // Footer
  'footer.about': { en: 'About Us', hi: 'हमारे बारे में', bn: 'আমাদের সম্পর্কে' },
  'footer.contact': { en: 'Contact', hi: 'संपर्क', bn: 'যোগাযোগ' },
  'footer.privacy': { en: 'Privacy Policy', hi: 'गोपनीयता नीति', bn: 'গোপনীয়তা নীতি' },
  'footer.terms': { en: 'Terms of Service', hi: 'सेवा की शर्तें', bn: 'পরিষেবার শর্তাবলী' },
  'footer.rights': { en: 'All rights reserved', hi: 'सर्वाधिकार सुरक्षित', bn: 'সর্বস্বত্ব সংরক্ষিত' },
  'footer.tagline': { en: 'AI-powered job portal for India. Search jobs, post listings, and apply fast.', hi: 'भारत के लिए AI-संचालित जॉब पोर्टल। नौकरियाँ खोजें, लिस्टिंग पोस्ट करें, और तेज़ी से आवेदन करें।', bn: 'ভারতের জন্য AI-চালিত চাকরি পোর্টাল। চাকরি খুঁজুন, তালিকা পোস্ট করুন এবং দ্রুত আবেদন করুন।' },
  'footer.forJobSeekers': { en: 'For Job Seekers', hi: 'नौकरी खोजने वालों के लिए', bn: 'চাকরি প্রার্থীদের জন্য' },
  'footer.forEmployers': { en: 'For Employers', hi: 'नियोक्ताओं के लिए', bn: 'নিয়োগকর্তাদের জন্য' },
  'footer.browseJobs': { en: 'Browse Jobs', hi: 'नौकरियाँ ब्राउज़ करें', bn: 'চাকরি ব্রাউজ করুন' },
  'footer.remoteJobs': { en: 'Remote Jobs', hi: 'रिमोट नौकरियाँ', bn: 'দূরবর্তী চাকরি' },
  'footer.fresherJobs': { en: 'Fresher Jobs', hi: 'फ्रेशर नौकरियाँ', bn: 'নবাগত চাকরি' },
  'footer.careerBlog': { en: 'Career Blog', hi: 'करियर ब्लॉग', bn: 'ক্যারিয়ার ব্লগ' },
  'footer.employerDashboard': { en: 'Employer Dashboard', hi: 'नियोक्ता डैशबोर्ड', bn: 'নিয়োগকর্তা ড্যাশবোর্ড' },
  'footer.company': { en: 'Company', hi: 'कंपनी', bn: 'কোম্পানি' },
  'footer.contactUs': { en: 'Contact Us', hi: 'संपर्क करें', bn: 'যোগাযোগ করুন' },
  'footer.termsOfUse': { en: 'Terms of Use', hi: 'उपयोग की शर्तें', bn: 'ব্যবহারের শর্তাবলী' },

  // 404 Page
  'notFound.title': { en: '404', hi: '404', bn: '404' },
  'notFound.message': { en: 'Oops! Page not found', hi: 'उफ़! पेज नहीं मिला', bn: 'উফ! পৃষ্ঠা পাওয়া যায়নি' },
  'notFound.returnHome': { en: 'Return to Home', hi: 'होम पर वापस जाएं', bn: 'হোমে ফিরে যান' },

  // Jobs Page
  'jobs.title': { en: 'Find Jobs', hi: 'नौकरियाँ खोजें', bn: 'চাকরি খুঁজুন' },
  'jobs.searchPlaceholder': { en: 'Search jobs, skills, companies...', hi: 'नौकरियाँ, कौशल, कंपनियाँ खोजें...', bn: 'চাকরি, দক্ষতা, কোম্পানি অনুসন্ধান করুন...' },
  'jobs.locationPlaceholder': { en: 'City or Remote', hi: 'शहर या रिमोट', bn: 'শহর বা দূরবর্তী' },
  'jobs.filters': { en: 'Filters', hi: 'फ़िल्टर', bn: 'ফিল্টার' },
  'jobs.jobType': { en: 'Job Type', hi: 'नौकरी का प्रकार', bn: 'চাকরির ধরন' },
  'jobs.experienceLevel': { en: 'Experience Level', hi: 'अनुभव स्तर', bn: 'অভিজ্ঞতার স্তর' },
  'jobs.salaryRange': { en: 'Salary Range (LPA)', hi: 'वेतन सीमा (LPA)', bn: 'বেতন পরিসীমা (LPA)' },
  'jobs.showing': { en: 'Showing', hi: 'दिखा रहे हैं', bn: 'দেখাচ্ছে' },
  'jobs.of': { en: 'of', hi: 'में से', bn: 'এর মধ্যে' },
  'jobs.jobsFound': { en: 'jobs', hi: 'नौकरियाँ', bn: 'চাকরি' },
  'jobs.newest': { en: 'Newest', hi: 'नवीनतम', bn: 'সর্বশেষ' },
  'jobs.oldest': { en: 'Oldest', hi: 'सबसे पुराना', bn: 'প্রাচীনতম' },
  'jobs.salaryHighLow': { en: 'Salary: High to Low', hi: 'वेतन: अधिक से कम', bn: 'বেতন: উচ্চ থেকে নিম্ন' },
  'jobs.salaryLowHigh': { en: 'Salary: Low to High', hi: 'वेतन: कम से अधिक', bn: 'বেতন: নিম্ন থেকে উচ্চ' },
  'jobs.noJobsFound': { en: 'No jobs found matching your criteria', hi: 'आपके मानदंडों से मेल खाती कोई नौकरी नहीं मिली', bn: 'আপনার মানদণ্ডের সাথে মেলে এমন কোন চাকরি পাওয়া যায়নি' },
  'jobs.tryAdjusting': { en: 'Try adjusting your search or filters', hi: 'अपनी खोज या फ़िल्टर समायोजित करने का प्रयास करें', bn: 'আপনার অনুসন্ধান বা ফিল্টার সামঞ্জস্য করার চেষ্টা করুন' },
  'jobs.postedAgo': { en: 'Posted', hi: 'पोस্ट किया गया', bn: 'পোস্ট করা হয়েছে' },

  // Profile
  'profile.title': { en: 'My Profile', hi: 'मेरी प्रोफ़ाइल', bn: 'আমার প্রোফাইল' },
  'profile.basicInfo': { en: 'Basic Information', hi: 'मूल जानकारी', bn: 'মৌলিক তথ্য' },
  'profile.basicInfoDesc': { en: 'Your public profile information', hi: 'आपकी सार्वजनिक प्रोफ़ाइल जानकारी', bn: 'আপনার সর্বজনীন প্রোফাইল তথ্য' },
  'profile.resume': { en: 'Resume', hi: 'रिज्यूमे', bn: 'জীবনবৃত্তান্ত' },
  'profile.resumeDesc': { en: 'Upload your resume for quick applications', hi: 'त्वरित आवेदनों के लिए अपना रिज्यूमे अपलोड करें', bn: 'দ্রুত আবেদনের জন্য আপনার জীবনবৃত্তান্ত আপলোড করুন' },
  'profile.skills': { en: 'Skills', hi: 'कौशल', bn: 'দক্ষতা' },
  'profile.skillsDesc': { en: 'Add your technical and soft skills', hi: 'अपनी तकनीकी और सॉफ्ट स्किल्स जोड़ें', bn: 'আপনার প্রযুক্তিগত এবং সফট স্কিল যোগ করুন' },
  'profile.experience': { en: 'Experience', hi: 'अनुभव', bn: 'অভিজ্ঞতা' },
  'profile.experienceDesc': { en: 'Your work history', hi: 'आपका कार्य इतिहास', bn: 'আপনার কাজের ইতিহাস' },
  'profile.education': { en: 'Education', hi: 'शिक्षा', bn: 'শিক্ষা' },
  'profile.educationDesc': { en: 'Your educational background', hi: 'आपकी शैक्षिक पृष्ठभूमि', bn: 'আপনার শিক্ষাগত পটভূমি' },
  'profile.socialLinks': { en: 'Social Links', hi: 'सोशल लिंक', bn: 'সামাজিক লিঙ্ক' },
  'profile.socialLinksDesc': { en: 'Connect your professional profiles', hi: 'अपनी पेशेवर प्रोफाइल कनेक्ट करें', bn: 'আপনার পেশাদার প্রোফাইল সংযুক্ত করুন' },
  'profile.jobPreferences': { en: 'Job Preferences', hi: 'नौकरी प्राथमिकताएं', bn: 'চাকরির পছন্দ' },
  'profile.jobPreferencesDesc': { en: 'Set your job search preferences', hi: 'अपनी नौकरी खोज प्राथमिकताएं सेट करें', bn: 'আপনার চাকরি অনুসন্ধান পছন্দ সেট করুন' },
  'profile.saveChanges': { en: 'Save Changes', hi: 'परिवर्तन सहेजें', bn: 'পরিবর্তন সংরক্ষণ করুন' },
  'profile.fullName': { en: 'Full Name', hi: 'पूरा नाम', bn: 'পুরো নাম' },
  'profile.phone': { en: 'Phone', hi: 'फोन', bn: 'ফোন' },
  'profile.location': { en: 'Location', hi: 'स्थान', bn: 'অবস্থান' },
  'profile.headline': { en: 'Professional Headline', hi: 'पेशेवर शीर्षक', bn: 'পেশাদার শিরোনাম' },
  'profile.aboutMe': { en: 'About Me', hi: 'मेरे बारे में', bn: 'আমার সম্পর্কে' },
  'profile.available': { en: 'Available for opportunities', hi: 'अवसरों के लिए उपलब्ध', bn: 'সুযোগের জন্য উপলব্ধ' },
  'profile.availableDesc': { en: 'Let employers know you\'re open to new roles', hi: 'नियोक्ताओं को बताएं कि आप नई भूमिकाओं के लिए खुले हैं', bn: 'নিয়োগকর্তাদের জানান যে আপনি নতুন ভূমিকার জন্য উন্মুক্ত' },
  'profile.resumeUploaded': { en: 'Resume uploaded', hi: 'रिज्यूमे अपलोड किया गया', bn: 'জীবনবৃত্তান্ত আপলোড হয়েছে' },
  'profile.viewResume': { en: 'View Resume', hi: 'रिज्यूमे देखें', bn: 'জীবনবৃত্তান্ত দেখুন' },
  'profile.uploadResume': { en: 'Upload your resume', hi: 'अपना रिज्यूमे अपलोड करें', bn: 'আপনার জীবনবৃত্তান্ত আপলোড করুন' },
  'profile.addSkill': { en: 'Add skill', hi: 'कौशल जोड़ें', bn: 'দক্ষতা যোগ করুন' },
  'profile.yearsExp': { en: 'Years of Experience', hi: 'अनुभव के वर्ष', bn: 'অভিজ্ঞতার বছর' },
  'profile.preferredJobTypes': { en: 'Preferred Job Types', hi: 'पसंदीदा नौकरी के प्रकार', bn: 'পছন্দের চাকরির ধরন' },
  'profile.expectedSalary': { en: 'Expected Salary Range', hi: 'अपेक्षित वेतन सीमा', bn: 'প্রত্যাশিত বেতন পরিসীমা' },
  'profile.minSalary': { en: 'Minimum (INR)', hi: 'न्यूनतम (INR)', bn: 'সর্বনিম্ন (INR)' },
  'profile.maxSalary': { en: 'Maximum (INR)', hi: 'अधिकतम (INR)', bn: 'সর্বোচ্চ (INR)' },
  'profile.addEducation': { en: 'Add Education', hi: 'शिक्षा जोड़ें', bn: 'শিক্ষা যোগ করুন' },
  'profile.addExperience': { en: 'Add Experience', hi: 'अनुभव जोड़ें', bn: 'অভিজ্ঞতা যোগ করুন' },
  'profile.present': { en: 'Present', hi: 'वर्तमान', bn: 'বর্তমান' },

  // Dashboard
  'dashboard.whatsHappening': { en: "Here's what's happening with your job search", hi: 'आपकी नौकरी खोज के साथ क्या हो रहा है', bn: 'আপনার চাকরির অনুসন্ধানে কী হচ্ছে' },
  'dashboard.totalApplications': { en: 'Total Applications', hi: 'कुल आवेदन', bn: 'মোট আবেদন' },
  'dashboard.inReview': { en: 'In Review', hi: 'समीक्षाधीन', bn: 'পর্যালোচনায়' },
  'dashboard.interviews': { en: 'Interviews', hi: 'इंटरव्यू', bn: 'ইন্টারভিউ' },
  'dashboard.completeProfile': { en: 'Complete Your Profile', hi: 'अपनी प्रोफ़ाइल पूरी करें', bn: 'আপনার প্রোফাইল সম্পূর্ণ করুন' },
  'dashboard.completeProfileDesc': { en: 'A complete profile increases your chances of getting hired', hi: 'एक पूर्ण प्रोफ़ाइल आपके नौकरी पाने की संभावना बढ़ाती है', bn: 'একটি সম্পূর্ণ প্রোফাইল আপনার নিয়োগ পাওয়ার সম্ভাবনা বাড়ায়' },
  'dashboard.tracker': { en: 'Tracker', hi: 'ट्रैकर', bn: 'ট্র্যাকার' },
  'dashboard.aiResume': { en: 'AI Resume', hi: 'AI रिज्यूमे', bn: 'AI জীবনবৃত্তান্ত' },
  'dashboard.noApplications': { en: 'No applications yet', hi: 'अभी तक कोई आवेदन नहीं', bn: 'এখনও কোন আবেদন নেই' },
  'dashboard.noApplicationsDesc': { en: 'Start applying to jobs to track your applications here', hi: 'अपने आवेदनों को यहां ट्रैक करने के लिए नौकरियों के लिए आवेदन करना शुरू करें', bn: 'এখানে আপনার আবেদন ট্র্যাক করতে চাকরিতে আবেদন করা শুরু করুন' },
  'dashboard.noSavedJobs': { en: 'No saved jobs', hi: 'कोई सेव की गई नौकरी नहीं', bn: 'কোন সংরক্ষিত চাকরি নেই' },
  'dashboard.noSavedJobsDesc': { en: 'Save jobs you\'re interested in to review later', hi: 'बाद में समीक्षा के लिए उन नौकरियों को सेव करें जिनमें आप रुचि रखते हैं', bn: 'পরে পর্যালোচনার জন্য আপনার আগ্রহী চাকরিগুলি সংরক্ষণ করুন' },
  'dashboard.editProfile': { en: 'Edit Profile', hi: 'प्रोफ़ाइल संपादित करें', bn: 'প্রোফাইল সম্পাদনা করুন' },
  'dashboard.browseJobs': { en: 'Browse Jobs', hi: 'नौकरियाँ ब्राउज़ करें', bn: 'চাকরি ব্রাউজ করুন' },
  'dashboard.aiMatchedJobs': { en: 'AI-Matched Jobs', hi: 'AI-मिलान नौकरियाँ', bn: 'AI-ম্যাচড চাকরি' },
  'dashboard.aiMatchedDesc': { en: 'Top job picks based on your profile', hi: 'आपकी प्रोफ़ाइल के आधार पर शीर्ष नौकरी चयन', bn: 'আপনার প্রোফাইলের উপর ভিত্তি করে শীর্ষ চাকরি পছন্দ' },
  'dashboard.match': { en: 'Match', hi: 'मिलान', bn: 'মিল' },
  'dashboard.viewAllMatches': { en: 'View All Matched Jobs', hi: 'सभी मिलान नौकरियाँ देखें', bn: 'সমস্ত মিলানো চাকরি দেখুন' },

  // Auth additional
  'auth.loginDesc': { en: 'Enter your credentials to access your account', hi: 'अपने खाते तक पहुंचने के लिए अपना क्रेडेंशियल दर्ज करें', bn: 'আপনার অ্যাকাউন্টে অ্যাক্সেস করতে আপনার শংসাপত্র লিখুন' },
  'auth.signupDesc': { en: 'Create an account to get started', hi: 'शुरू करने के लिए एक खाता बनाएं', bn: 'শুরু করতে একটি অ্যাকাউন্ট তৈরি করুন' },
  'auth.continueWithGoogle': { en: 'Continue with Google', hi: 'Google के साथ जारी रखें', bn: 'Google দিয়ে চালিয়ে যান' },
  'auth.phoneSignup': { en: 'Sign up with phone number instead', hi: 'इसके बजाय फोन नंबर से साइन अप करें', bn: 'পরিবর্তে ফোন নম্বর দিয়ে সাইন আপ করুন' },
  'auth.passwordMinLength': { en: 'Password must be at least 6 characters', hi: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए', bn: 'পাসওয়ার্ড কমপক্ষে 6 অক্ষরের হতে হবে' },
  'auth.agreeTerms': { en: 'By signing up, you agree to our', hi: 'साइन अप करके, आप हमारी स्वीकार करते हैं', bn: 'সাইন আপ করে, আপনি আমাদের সম্মত হন' },

  // Featured Jobs
  'featuredJobs.featured': { en: 'Featured', hi: 'विशेष', bn: 'বৈশিষ্ট্যযুক্ত' },
  'featuredJobs.topOpportunities': { en: 'Top opportunities from leading companies', hi: 'अग्रणी कंपनियों से शीर्ष अवसर', bn: 'শীর্ষস্থানীয় কোম্পানিগুলি থেকে শীর্ষ সুযোগ' },
  'featuredJobs.notDisclosed': { en: 'Not disclosed', hi: 'खुलासा नहीं किया गया', bn: 'প্রকাশিত নয়' },

  // Job card
  'jobCard.company': { en: 'Company', hi: 'कंपनी', bn: 'কোম্পানি' },
  'jobCard.loginRequired': { en: 'Login Required', hi: 'लॉगिन आवश्यक', bn: 'লগইন প্রয়োজন' },
  'jobCard.loginToSave': { en: 'Please login to save jobs', hi: 'नौकरियाँ सेव करने के लिए कृपया लॉगिन करें', bn: 'চাকরি সংরক্ষণ করতে অনুগ্রহ করে লগইন করুন' },
  'jobCard.jobSaved': { en: 'Job saved!', hi: 'नौकरी सेव हो गई!', bn: 'চাকরি সংরক্ষিত!' },
  'jobCard.jobRemoved': { en: 'Job removed from saved', hi: 'नौकरी सेव से हटा दी गई', bn: 'চাকরি সংরক্ষিত থেকে সরানো হয়েছে' },

  // Chat bot — Government Jobs Assistant
  'chat.title': { en: 'TrueJobs सरकारी सहायक', hi: 'TrueJobs सरकारी सहायक', bn: 'TrueJobs সরকারি সহায়ক' },
  'chat.subtitle': { en: 'Government Jobs Assistant', hi: 'सरकारी नौकरी सहायक', bn: 'সরকারি চাকরি সহায়ক' },
  'chat.placeholder': { en: 'Ask about govt jobs, exams...', hi: 'सरकारी नौकरी के बारे में पूछें...', bn: 'সরকারি চাকরি সম্পর্কে জিজ্ঞাসা করুন...' },
  'chat.tryThese': { en: 'Try these:', hi: 'ये आज़माएं:', bn: 'এগুলি চেষ্টা করুন:' },
  'chat.hint': { en: 'Try: "SSC CGL eligibility kya hai?"', hi: 'आज़माएं: "SSC CGL eligibility kya hai?"', bn: 'চেষ্টা করুন: "SSC CGL eligibility kya hai?"' },
  'chat.tooltipTitle': { en: 'Sarkari Jobs AI Assistant', hi: 'सरकारी नौकरी AI सहायक', bn: 'সরকারি চাকরি AI সহায়ক' },
  'chat.tooltipDesc': { en: 'Get info on govt jobs, exams, admit cards, results', hi: 'सरकारी नौकरी, परीक्षा, एडमिट कार्ड, रिज़ल्ट की जानकारी पाएं', bn: 'সরকারি চাকরি, পরীক্ষা, অ্যাডমিট কার্ড, রেজাল্টের তথ্য পান' },
  'chat.greeting': { en: "Hi! 👋 I'm the TrueJobs Sarkari Jobs Assistant. Ask me about government jobs, exams, eligibility, admit cards, results, syllabus, and more!", hi: "नमस्ते! 👋 मैं TrueJobs सरकारी नौकरी सहायक हूं। सरकारी नौकरी, परीक्षा, पात्रता, एडमिट कार्ड, रिज़ल्ट, सिलेबस के बारे में पूछें!", bn: "হাই! 👋 আমি TrueJobs সরকারি চাকরি সহায়ক। সরকারি চাকরি, পরীক্ষা, যোগ্যতা, অ্যাডমিট কার্ড, রেজাল্ট, সিলেবাস সম্পর্কে জিজ্ঞাসা করুন!" },

  // Language names
  'language.english': { en: 'English', hi: 'अंग्रेज़ी', bn: 'ইংরেজি' },
  'language.hindi': { en: 'हिंदी', hi: 'हिंदी', bn: 'হিন্দি' },
  'language.bengali': { en: 'বাংলা', hi: 'बंगाली', bn: 'বাংলা' },
  'language.switchTo': { en: 'Switch language', hi: 'भाषा बदलें', bn: 'ভাষা পরিবর্তন করুন' },


  // Job Detail Page
  'jobDetail.backToJobs': { en: 'Back to Jobs', hi: 'नौकरियों पर वापस', bn: 'চাকরিতে ফিরে যান' },
  'jobDetail.jobNotFound': { en: 'Job Not Found', hi: 'नौकरी नहीं मिली', bn: 'চাকরি পাওয়া যায়নি' },
  'jobDetail.jobNotFoundDesc': { en: 'This job may have been removed or is no longer available.', hi: 'यह नौकरी हटा दी गई है या अब उपलब्ध नहीं है।', bn: 'এই চাকরিটি সরিয়ে দেওয়া হয়েছে বা আর উপলব্ধ নেই।' },
  'jobDetail.browseAllJobs': { en: 'Browse All Jobs', hi: 'सभी नौकरियाँ ब्राउज़ करें', bn: 'সমস্ত চাকরি ব্রাউজ করুন' },
  'jobDetail.featured': { en: 'Featured', hi: 'विशेष', bn: 'বৈশিষ্ট্যযুক্ত' },
  'jobDetail.posted': { en: 'Posted', hi: 'पोस्ट किया गया', bn: 'পোস্ট করা হয়েছে' },
  'jobDetail.jobDescription': { en: 'Job Description', hi: 'नौकरी विवरण', bn: 'চাকরির বিবরণ' },
  'jobDetail.requirements': { en: 'Requirements', hi: 'आवश्यकताएं', bn: 'প্রয়োজনীয়তা' },
  'jobDetail.responsibilities': { en: 'Responsibilities', hi: 'जिम्मेदारियाँ', bn: 'দায়িত্ব' },
  'jobDetail.requiredSkills': { en: 'Required Skills', hi: 'आवश्यक कौशल', bn: 'প্রয়োজনীয় দক্ষতা' },
  'jobDetail.benefits': { en: 'Benefits & Perks', hi: 'लाभ और सुविधाएं', bn: 'সুবিধা এবং পার্কস' },
  'jobDetail.applicationSubmitted': { en: 'Application Submitted', hi: 'आवेदन जमा हो गया', bn: 'আবেদন জমা দেওয়া হয়েছে' },
  'jobDetail.applied': { en: 'Applied', hi: 'आवेदन किया', bn: 'আবেদন করা হয়েছে' },
  'jobDetail.status': { en: 'Status', hi: 'स्थिति', bn: 'অবস্থা' },
  'jobDetail.applyForThisJob': { en: 'Apply for this job', hi: 'इस नौकरी के लिए आवेदन करें', bn: 'এই চাকরির জন্য আবেদন করুন' },
  'jobDetail.uploadResumeHint': { en: 'Upload your resume in your profile for better chances!', hi: 'बेहतर मौकों के लिए अपनी प्रोफ़ाइल में अपना रिज्यूमे अपलोड करें!', bn: 'ভালো সুযোগের জন্য আপনার প্রোফাইলে জীবনবৃত্তান্ত আপলোড করুন!' },
  'jobDetail.applicants': { en: 'applicants', hi: 'आवेदक', bn: 'আবেদনকারী' },
  'jobDetail.saveJob': { en: 'Save Job', hi: 'नौकरी सेव करें', bn: 'চাকরি সংরক্ষণ করুন' },
  'jobDetail.aboutCompany': { en: 'About the Company', hi: 'कंपनी के बारे में', bn: 'কোম্পানি সম্পর্কে' },
  'jobDetail.companySize': { en: 'Company Size', hi: 'कंपनी का आकार', bn: 'কোম্পানির আকার' },
  'jobDetail.industry': { en: 'Industry', hi: 'उद्योग', bn: 'শিল্প' },
  'jobDetail.website': { en: 'Website', hi: 'वेबसाइट', bn: 'ওয়েবসাইট' },
  'jobDetail.visitWebsite': { en: 'Visit Website', hi: 'वेबसाइट देखें', bn: 'ওয়েবসাইট দেখুন' },
  'jobDetail.viewCompanyProfile': { en: 'View Company Profile', hi: 'कंपनी प्रोफ़ाइल देखें', bn: 'কোম্পানি প্রোফাইল দেখুন' },
  'jobDetail.notDisclosed': { en: 'Not disclosed', hi: 'खुलासा नहीं किया गया', bn: 'প্রকাশিত নয়' },
  'jobDetail.perYear': { en: 'per year', hi: 'प्रति वर्ष', bn: 'প্রতি বছর' },
  'jobDetail.linkCopied': { en: 'Link copied to clipboard!', hi: 'लिंक क्लिपबोर्ड पर कॉपी हो गया!', bn: 'লিঙ্ক ক্লিপবোর্ডে কপি হয়েছে!' },
  'jobDetail.loginRequired': { en: 'Login Required', hi: 'लॉगिन आवश्यक', bn: 'লগইন প্রয়োজন' },
  'jobDetail.loginToSave': { en: 'Please login to save jobs', hi: 'नौकरियाँ सेव करने के लिए लॉगिन करें', bn: 'চাকরি সংরক্ষণ করতে লগইন করুন' },
  'jobDetail.loginToApply': { en: 'Please login to apply for jobs', hi: 'नौकरियों के लिए आवेदन करने के लिए लॉगिन करें', bn: 'চাকরির জন্য আবেদন করতে লগইন করুন' },
  'jobDetail.onlyJobSeekers': { en: 'Only job seekers can apply to jobs', hi: 'केवल नौकरी खोजने वाले ही नौकरियों के लिए आवेदन कर सकते हैं', bn: 'শুধুমাত্র চাকরি প্রার্থীরা চাকরির জন্য আবেদন করতে পারেন' },
  'jobDetail.applicationFailed': { en: 'Application Failed', hi: 'आवेदन विफल', bn: 'আবেদন ব্যর্থ' },
  'jobDetail.applicationSuccess': { en: 'Application Submitted!', hi: 'आवेदन जमा हो गया!', bn: 'আবেদন জমা হয়েছে!' },
  'jobDetail.applicationSuccessDesc': { en: 'Your application has been sent to the employer.', hi: 'आपका आवेदन नियोक्ता को भेज दिया गया है।', bn: 'আপনার আবেদন নিয়োগকর্তাকে পাঠানো হয়েছে।' },
  'jobDetail.coverLetter': { en: 'Cover Letter', hi: 'कवर लेटर', bn: 'কভার লেটার' },
  'jobDetail.coverLetterPlaceholder': { en: 'Write a brief cover letter explaining why you are a good fit for this role...', hi: 'इस भूमिका के लिए आप क्यों उपयुक्त हैं, इसे समझाते हुए एक संक्षिप्त कवर लेटर लिखें...', bn: 'এই ভূমিকার জন্য আপনি কেন উপযুক্ত তা ব্যাখ্যা করে একটি সংক্ষিপ্ত কভার লেটার লিখুন...' },
  'jobDetail.submitApplication': { en: 'Submit Application', hi: 'आवेदन जमा करें', bn: 'আবেদন জমা দিন' },
  'jobDetail.submitting': { en: 'Submitting...', hi: 'जमा हो रहा है...', bn: 'জমা হচ্ছে...' },

  // Experience Levels (extended)
  'exp.fresherYears': { en: 'Fresher (0-1 years)', hi: 'फ्रेशर (0-1 वर्ष)', bn: 'নবাগত (0-1 বছর)' },
  'exp.juniorYears': { en: 'Junior (1-2 years)', hi: 'जूनियर (1-2 वर्ष)', bn: 'জুনিয়র (1-2 বছর)' },
  'exp.midYears': { en: 'Mid Level (3-5 years)', hi: 'मध्य स्तर (3-5 वर्ष)', bn: 'মাঝারি স্তর (3-5 বছর)' },
  'exp.seniorYears': { en: 'Senior (5-8 years)', hi: 'सीनियर (5-8 वर्ष)', bn: 'সিনিয়র (5-8 বছর)' },
  'exp.leadYears': { en: 'Lead (8+ years)', hi: 'लीड (8+ वर्ष)', bn: 'লিড (8+ বছর)' },

  // Forgot Password Page
  'forgotPassword.title': { en: 'Reset Password', hi: 'पासवर्ड रीसेट करें', bn: 'পাসওয়ার্ড রিসেট করুন' },
  'forgotPassword.subtitle': { en: "Choose how you'd like to reset your password", hi: 'चुनें कि आप अपना पासवर्ड कैसे रीसेट करना चाहते हैं', bn: 'আপনি কীভাবে আপনার পাসওয়ার্ড রিসেট করতে চান তা বেছে নিন' },
  'forgotPassword.email': { en: 'Email', hi: 'ईमेल', bn: 'ইমেল' },
  'forgotPassword.phone': { en: 'Phone', hi: 'फोन', bn: 'ফোন' },
  'forgotPassword.emailAddress': { en: 'Email Address', hi: 'ईमेल पता', bn: 'ইমেল ঠিকানা' },
  'forgotPassword.phoneNumber': { en: 'Phone Number', hi: 'फोन नंबर', bn: 'ফোন নম্বর' },
  'forgotPassword.sendResetLink': { en: 'Send Reset Link', hi: 'रीसेट लिंक भेजें', bn: 'রিসেট লিঙ্ক পাঠান' },
  'forgotPassword.sendOTP': { en: 'Send OTP', hi: 'OTP भेजें', bn: 'OTP পাঠান' },
  'forgotPassword.verifyOTP': { en: 'Verify OTP', hi: 'OTP सत्यापित करें', bn: 'OTP যাচাই করুন' },
  'forgotPassword.newPassword': { en: 'New Password', hi: 'नया पासवर्ड', bn: 'নতুন পাসওয়ার্ড' },
  'forgotPassword.confirmPassword': { en: 'Confirm Password', hi: 'पासवर्ड की पुष्टि करें', bn: 'পাসওয়ার্ড নিশ্চিত করুন' },
  'forgotPassword.resetPassword': { en: 'Reset Password', hi: 'पासवर्ड रीसेट करें', bn: 'পাসওয়ার্ড রিসেট করুন' },
  'forgotPassword.rememberPassword': { en: 'Remember your password?', hi: 'अपना पासवर्ड याद है?', bn: 'আপনার পাসওয়ার্ড মনে আছে?' },
  'forgotPassword.didntReceive': { en: "Didn't receive the code?", hi: 'कोड नहीं मिला?', bn: 'কোড পাননি?' },
  'forgotPassword.resend': { en: 'Resend', hi: 'पुनः भेजें', bn: 'পুনরায় পাঠান' },
  'forgotPassword.resetLinkSent': { en: 'Reset Link Sent', hi: 'रीसेट लिंक भेजा गया', bn: 'রিসেট লিঙ্ক পাঠানো হয়েছে' },
  'forgotPassword.checkEmail': { en: 'Check your email for the password reset link.', hi: 'पासवर्ड रीसेट लिंक के लिए अपना ईमेल देखें।', bn: 'পাসওয়ার্ড রিসেট লিঙ্কের জন্য আপনার ইমেল দেখুন।' },
  'forgotPassword.otpSent': { en: 'OTP Sent', hi: 'OTP भेजा गया', bn: 'OTP পাঠানো হয়েছে' },
  'forgotPassword.checkPhone': { en: 'Please check your phone for the verification code.', hi: 'कृपया सत्यापन कोड के लिए अपना फोन देखें।', bn: 'অনুগ্রহ করে যাচাইকরণ কোডের জন্য আপনার ফোন দেখুন।' },
  'forgotPassword.phoneVerified': { en: 'Phone Verified', hi: 'फोन सत्यापित', bn: 'ফোন যাচাই হয়েছে' },
  'forgotPassword.setNewPassword': { en: 'Now set your new password.', hi: 'अब अपना नया पासवर्ड सेट करें।', bn: 'এখন আপনার নতুন পাসওয়ার্ড সেট করুন।' },
  'forgotPassword.passwordsDoNotMatch': { en: 'Passwords do not match.', hi: 'पासवर्ड मेल नहीं खाते।', bn: 'পাসওয়ার্ড মিলছে না।' },
  'forgotPassword.passwordReset': { en: 'Password Reset', hi: 'पासवर्ड रीसेट', bn: 'পাসওয়ার্ড রিসেট' },
  'forgotPassword.passwordResetSuccess': { en: 'Your password has been reset. Please log in.', hi: 'आपका पासवर्ड रीसेट हो गया है। कृपया लॉगिन करें।', bn: 'আপনার পাসওয়ার্ড রিসেট হয়েছে। অনুগ্রহ করে লগইন করুন।' },

  // Phone Signup Page
  'phoneSignup.title': { en: 'Sign Up with Phone', hi: 'फोन से साइन अप करें', bn: 'ফোন দিয়ে সাইন আপ করুন' },
  'phoneSignup.verifyPhone': { en: 'Verify Your Phone', hi: 'अपना फोन सत्यापित करें', bn: 'আপনার ফোন যাচাই করুন' },
  'phoneSignup.completeRegistration': { en: 'Complete Registration', hi: 'पंजीकरण पूर्ण करें', bn: 'নিবন্ধন সম্পূর্ণ করুন' },
  'phoneSignup.enterPhone': { en: 'Enter your phone number to get started', hi: 'शुरू करने के लिए अपना फोन नंबर दर्ज करें', bn: 'শুরু করতে আপনার ফোন নম্বর লিখুন' },
  'phoneSignup.enterOTP': { en: 'Enter the 6-digit code sent to your phone', hi: 'अपने फोन पर भेजा गया 6-अंकीय कोड दर्ज करें', bn: 'আপনার ফোনে পাঠানো 6-সংখ্যার কোড লিখুন' },
  'phoneSignup.fillDetails': { en: 'Fill in your details to create your account', hi: 'अपना खाता बनाने के लिए अपना विवरण भरें', bn: 'আপনার অ্যাকাউন্ট তৈরি করতে আপনার বিবরণ পূরণ করুন' },
  'phoneSignup.phoneNumber': { en: 'Phone Number', hi: 'फोन नंबर', bn: 'ফোন নম্বর' },
  'phoneSignup.includeCountryCode': { en: 'Include country code (e.g., +91 for India)', hi: 'देश का कोड शामिल करें (जैसे, भारत के लिए +91)', bn: 'দেশের কোড অন্তর্ভুক্ত করুন (যেমন, ভারতের জন্য +91)' },
  'phoneSignup.sendOTP': { en: 'Send OTP', hi: 'OTP भेजें', bn: 'OTP পাঠান' },
  'phoneSignup.verifyOTP': { en: 'Verify OTP', hi: 'OTP सत्यापित करें', bn: 'OTP যাচাই করুন' },
  'phoneSignup.didntReceive': { en: "Didn't receive the code?", hi: 'कोड नहीं मिला?', bn: 'কোড পাননি?' },
  'phoneSignup.resend': { en: 'Resend', hi: 'पुनः भेजें', bn: 'পুনরায় পাঠান' },
  'phoneSignup.createAccount': { en: 'Create Account', hi: 'खाता बनाएं', bn: 'অ্যাকাউন্ট তৈরি করুন' },
  'phoneSignup.preferEmail': { en: 'Prefer email?', hi: 'ईमेल पसंद करते हैं?', bn: 'ইমেল পছন্দ করেন?' },
  'phoneSignup.signUpWithEmail': { en: 'Sign up with email', hi: 'ईमेल से साइन अप करें', bn: 'ইমেল দিয়ে সাইন আপ করুন' },
  'phoneSignup.otpSent': { en: 'OTP Sent', hi: 'OTP भेजा गया', bn: 'OTP পাঠানো হয়েছে' },
  'phoneSignup.checkPhone': { en: 'Please check your phone for the verification code.', hi: 'कृपया सत्यापन कोड के लिए अपना फोन देखें।', bn: 'অনুগ্রহ করে যাচাইকরণ কোডের জন্য আপনার ফোন দেখুন।' },
  'phoneSignup.phoneVerified': { en: 'Phone Verified', hi: 'फोन सत्यापित', bn: 'ফোন যাচাই হয়েছে' },
  'phoneSignup.completeReg': { en: 'Please complete your registration.', hi: 'कृपया अपना पंजीकरण पूर्ण करें।', bn: 'অনুগ্রহ করে আপনার নিবন্ধন সম্পূর্ণ করুন।' },
  'phoneSignup.accountCreated': { en: 'Account Created', hi: 'खाता बनाया गया', bn: 'অ্যাকাউন্ট তৈরি হয়েছে' },
  'phoneSignup.welcomeMessage': { en: 'Welcome! Your account has been created successfully.', hi: 'स्वागत है! आपका खाता सफलतापूर्वक बना दिया गया है।', bn: 'স্বাগতম! আপনার অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে।' },

  // Employer Dashboard
  'employerDash.title': { en: 'Employer Dashboard', hi: 'नियोक्ता डैशबोर्ड', bn: 'নিয়োগকর্তা ড্যাশবোর্ড' },
  'employerDash.manageJobsApplicants': { en: 'Manage your jobs and applicants', hi: 'अपनी नौकरियों और आवेदकों का प्रबंधन करें', bn: 'আপনার চাকরি এবং আবেদনকারীদের পরিচালনা করুন' },
  'employerDash.companyProfile': { en: 'Company Profile', hi: 'कंपनी प्रोफ़ाइल', bn: 'কোম্পানি প্রোফাইল' },
  'employerDash.postJob': { en: 'Post a Job', hi: 'नौकरी पोस्ट करें', bn: 'চাকরি পোস্ট করুন' },
  'employerDash.setupCompany': { en: 'Set Up Your Company Profile', hi: 'अपनी कंपनी प्रोफ़ाइल सेट करें', bn: 'আপনার কোম্পানি প্রোফাইল সেট আপ করুন' },
  'employerDash.beforePosting': { en: 'Before you can post jobs, you need to create your company profile.', hi: 'नौकरी पोस्ट करने से पहले, आपको अपनी कंपनी प्रोफ़ाइल बनानी होगी।', bn: 'চাকরি পোস্ট করার আগে, আপনাকে আপনার কোম্পানি প্রোফাইল তৈরি করতে হবে।' },
  'employerDash.createCompanyProfile': { en: 'Create Company Profile', hi: 'कंपनी प्रोफ़ाइल बनाएं', bn: 'কোম্পানি প্রোফাইল তৈরি করুন' },
  'employerDash.pendingApproval': { en: 'Company Pending Approval', hi: 'कंपनी स्वीकृति के लिए लंबित', bn: 'কোম্পানি অনুমোদনের জন্য মুলতুবি' },
  'employerDash.pendingApprovalDesc': { en: 'Your company profile is under review. Jobs will be visible once approved.', hi: 'आपकी कंपनी प्रोफ़ाइल समीक्षाधीन है। स्वीकृत होने के बाद नौकरियाँ दिखाई देंगी।', bn: 'আপনার কোম্পানি প্রোফাইল পর্যালোচনাধীন। অনুমোদিত হলে চাকরি দেখা যাবে।' },
  'employerDash.totalJobs': { en: 'Total Jobs', hi: 'कुल नौकरियाँ', bn: 'মোট চাকরি' },
  'employerDash.activeJobs': { en: 'Active Jobs', hi: 'सक्रिय नौकरियाँ', bn: 'সক্রিয় চাকরি' },
  'employerDash.totalApplications': { en: 'Total Applications', hi: 'कुल आवेदन', bn: 'মোট আবেদন' },
  'employerDash.totalViews': { en: 'Total Views', hi: 'कुल व्यूज', bn: 'মোট ভিউ' },
  'employerDash.viewManageJobs': { en: 'View and manage your job postings', hi: 'अपनी नौकरी पोस्टिंग देखें और प्रबंधित करें', bn: 'আপনার চাকরি পোস্টিং দেখুন এবং পরিচালনা করুন' },
  'employerDash.viewAll': { en: 'View All', hi: 'सभी देखें', bn: 'সব দেখুন' },
  'employerDash.noJobsPosted': { en: 'No jobs posted yet', hi: 'अभी तक कोई नौकरी पोस्ट नहीं की गई', bn: 'এখনও কোন চাকরি পোস্ট করা হয়নি' },
  'employerDash.createFirstJob': { en: 'Create your first job posting to start receiving applications', hi: 'आवेदन प्राप्त करना शुरू करने के लिए अपनी पहली नौकरी पोस्टिंग बनाएं', bn: 'আবেদন পেতে শুরু করতে আপনার প্রথম চাকরি পোস্টিং তৈরি করুন' },
  'employerDash.applicants': { en: 'applicants', hi: 'आवेदक', bn: 'আবেদনকারী' },
  'employerDash.views': { en: 'views', hi: 'व्यूज', bn: 'ভিউ' },
  'employerDash.edit': { en: 'Edit', hi: 'संपादित करें', bn: 'সম্পাদনা করুন' },
  'employerDash.viewApplicants': { en: 'View Applicants', hi: 'आवेदक देखें', bn: 'আবেদনকারী দেখুন' },
  'employerDash.pause': { en: 'Pause', hi: 'रोकें', bn: 'বিরতি' },
  'employerDash.activate': { en: 'Activate', hi: 'सक्रिय करें', bn: 'সক্রিয় করুন' },
  'employerDash.close': { en: 'Close', hi: 'बंद करें', bn: 'বন্ধ করুন' },
  'employerDash.delete': { en: 'Delete', hi: 'हटाएं', bn: 'মুছুন' },
  'employerDash.recentApplications': { en: 'Recent Applications', hi: 'हाल के आवेदन', bn: 'সাম্প্রতিক আবেদন' },
  'employerDash.noApplicationsYet': { en: 'No applications yet', hi: 'अभी तक कोई आवेदन नहीं', bn: 'এখনও কোন আবেদন নেই' },
  'employerDash.appliedFor': { en: 'Applied for', hi: 'के लिए आवेदन किया', bn: 'এর জন্য আবেদন করেছে' },
  'employerDash.anonymous': { en: 'Anonymous', hi: 'अज्ञात', bn: 'বেনামী' },
  'employerDash.jobActivated': { en: 'Job activated', hi: 'नौकरी सक्रिय की गई', bn: 'চাকরি সক্রিয় করা হয়েছে' },
  'employerDash.jobDeleted': { en: 'Job deleted', hi: 'नौकरी हटाई गई', bn: 'চাকরি মুছে ফেলা হয়েছে' },

  // Company Profile Page
  'companyProfile.createTitle': { en: 'Create Company Profile', hi: 'कंपनी प्रोफ़ाइल बनाएं', bn: 'কোম্পানি প্রোফাইল তৈরি করুন' },
  'companyProfile.editTitle': { en: 'Company Profile', hi: 'कंपनी प्रोफ़ाइल', bn: 'কোম্পানি প্রোফাইল' },
  'companyProfile.setupDesc': { en: 'Set up your company to start posting jobs', hi: 'नौकरियाँ पोस्ट करना शुरू करने के लिए अपनी कंपनी सेट करें', bn: 'চাকরি পোস্ট করা শুরু করতে আপনার কোম্পানি সেট আপ করুন' },
  'companyProfile.manageDesc': { en: 'Manage your company information', hi: 'अपनी कंपनी की जानकारी प्रबंधित करें', bn: 'আপনার কোম্পানির তথ্য পরিচালনা করুন' },
  'companyProfile.createCompany': { en: 'Create Company', hi: 'कंपनी बनाएं', bn: 'কোম্পানি তৈরি করুন' },
  'companyProfile.saveChanges': { en: 'Save Changes', hi: 'परिवर्तन सहेजें', bn: 'পরিবর্তন সংরক্ষণ করুন' },
  'companyProfile.branding': { en: 'Branding', hi: 'ब्रांडिंग', bn: 'ব্র্যান্ডিং' },
  'companyProfile.brandingDesc': { en: 'Upload your company logo and cover image', hi: 'अपनी कंपनी का लोगो और कवर इमेज अपलोड करें', bn: 'আপনার কোম্পানির লোগো এবং কভার ইমেজ আপলোড করুন' },
  'companyProfile.companyLogo': { en: 'Company Logo', hi: 'कंपनी लोगो', bn: 'কোম্পানি লোগো' },
  'companyProfile.logoRecommended': { en: 'Recommended: 200x200px, PNG or JPG', hi: 'अनुशंसित: 200x200px, PNG या JPG', bn: 'প্রস্তাবিত: 200x200px, PNG বা JPG' },
  'companyProfile.coverImage': { en: 'Cover Image', hi: 'कवर इमेज', bn: 'কভার ইমেজ' },
  'companyProfile.clickToUpload': { en: 'Click to upload cover image', hi: 'कवर इमेज अपलोड करने के लिए क्लिक करें', bn: 'কভার ইমেজ আপলোড করতে ক্লিক করুন' },
  'companyProfile.coverRecommended': { en: 'Recommended: 1200x300px, PNG or JPG', hi: 'अनुशंसित: 1200x300px, PNG या JPG', bn: 'প্রস্তাবিত: 1200x300px, PNG বা JPG' },
  'companyProfile.basicInfo': { en: 'Basic Information', hi: 'मूल जानकारी', bn: 'মৌলিক তথ্য' },
  'companyProfile.companyName': { en: 'Company Name', hi: 'कंपनी का नाम', bn: 'কোম্পানির নাম' },
  'companyProfile.urlSlug': { en: 'URL Slug', hi: 'URL स्लग', bn: 'URL স্লাগ' },
  'companyProfile.aboutCompany': { en: 'About the Company', hi: 'कंपनी के बारे में', bn: 'কোম্পানি সম্পর্কে' },
  'companyProfile.aboutPlaceholder': { en: 'Tell potential candidates about your company, culture, and mission...', hi: 'संभावित उम्मीदवारों को अपनी कंपनी, संस्कृति और मिशन के बारे में बताएं...', bn: 'সম্ভাব্য প্রার্থীদের আপনার কোম্পানি, সংস্কৃতি এবং মিশন সম্পর্কে বলুন...' },
  'companyProfile.industry': { en: 'Industry', hi: 'उद्योग', bn: 'শিল্প' },
  'companyProfile.selectIndustry': { en: 'Select industry', hi: 'उद्योग चुनें', bn: 'শিল্প নির্বাচন করুন' },
  'companyProfile.companySize': { en: 'Company Size', hi: 'कंपनी का आकार', bn: 'কোম্পানির আকার' },
  'companyProfile.selectSize': { en: 'Select size', hi: 'आकार चुनें', bn: 'আকার নির্বাচন করুন' },
  'companyProfile.employees': { en: 'employees', hi: 'कर्मचारी', bn: 'কর্মচারী' },
  'companyProfile.foundedYear': { en: 'Founded Year', hi: 'स्थापना वर्ष', bn: 'প্রতিষ্ঠার বছর' },
  'companyProfile.headquarters': { en: 'Headquarters Location', hi: 'मुख्यालय स्थान', bn: 'সদর দপ্তরের অবস্থান' },
  'companyProfile.onlinePresence': { en: 'Online Presence', hi: 'ऑनलाइन उपस्थिति', bn: 'অনলাইন উপস্থিতি' },
  'companyProfile.onlinePresenceDesc': { en: "Add links to your company's online profiles", hi: 'अपनी कंपनी की ऑनलाइन प्रोफ़ाइल के लिंक जोड़ें', bn: 'আপনার কোম্পানির অনলাইন প্রোফাইলের লিঙ্ক যোগ করুন' },
  'companyProfile.website': { en: 'Website', hi: 'वेबसाइट', bn: 'ওয়েবসাইট' },
  'companyProfile.linkedin': { en: 'LinkedIn', hi: 'लिंक्डइन', bn: 'লিংকডইন' },
  'companyProfile.companyNameRequired': { en: 'Company name is required', hi: 'कंपनी का नाम आवश्यक है', bn: 'কোম্পানির নাম প্রয়োজন' },
  'companyProfile.companyCreated': { en: 'Company created!', hi: 'कंपनी बनाई गई!', bn: 'কোম্পানি তৈরি হয়েছে!' },
  'companyProfile.companyUpdated': { en: 'Company updated!', hi: 'कंपनी अपडेट हो गई!', bn: 'কোম্পানি আপডেট হয়েছে!' },
  'companyProfile.logoUploaded': { en: 'Logo uploaded!', hi: 'लोगो अपलोड हो गया!', bn: 'লোগো আপলোড হয়েছে!' },
  'companyProfile.coverUploaded': { en: 'Cover image uploaded!', hi: 'कवर इमेज अपलोड हो गई!', bn: 'কভার ইমেজ আপলোড হয়েছে!' },
  'companyProfile.uploadFailed': { en: 'Upload failed', hi: 'अपलोड विफल', bn: 'আপলোড ব্যর্থ' },

  // Job Posting Wizard
  'wizard.postJob': { en: 'Post Job', hi: 'नौकरी पोस्ट करें', bn: 'চাকরি পোস্ট করুন' },
  'wizard.step1': { en: 'Job details', hi: 'नौकरी विवरण', bn: 'চাকরির বিবরণ' },
  'wizard.step2': { en: 'Candidate requirements', hi: 'उम्मीदवार आवश्यकताएं', bn: 'প্রার্থীর প্রয়োজনীয়তা' },
  'wizard.step3': { en: 'Interview information', hi: 'साक्षात्कार जानकारी', bn: 'ইন্টারভিউ তথ্য' },
  'wizard.step4': { en: 'Job preview', hi: 'नौकरी पूर्वावलोकन', bn: 'চাকরির পূর্বরূপ' },
  'wizard.step5': { en: 'Choose plan', hi: 'योजना चुनें', bn: 'পরিকল্পনা নির্বাচন করুন' },
  'wizard.continue': { en: 'Continue', hi: 'जारी रखें', bn: 'চালিয়ে যান' },
  'wizard.back': { en: 'Back', hi: 'वापस', bn: 'পিছনে' },
  'wizard.companyRequired': { en: 'Company Required', hi: 'कंपनी आवश्यक', bn: 'কোম্পানি প্রয়োজন' },
  'wizard.createCompanyFirst': { en: 'Please create a company profile first', hi: 'कृपया पहले एक कंपनी प्रोफ़ाइल बनाएं', bn: 'প্রথমে একটি কোম্পানি প্রোফাইল তৈরি করুন' },
  'wizard.jobPostedSuccess': { en: 'Job Posted Successfully!', hi: 'नौकरी सफलतापूर्वक पोस्ट हुई!', bn: 'চাকরি সফলভাবে পোস্ট হয়েছে!' },
  'wizard.jobSubmittedApproval': { en: 'Job Submitted for Approval', hi: 'नौकरी अनुमोदन के लिए जमा', bn: 'চাকরি অনুমোদনের জন্য জমা দেওয়া হয়েছে' },
  'wizard.jobLive': { en: 'Your job is now live and visible to candidates.', hi: 'आपकी नौकरी अब लाइव है और उम्मीदवारों को दिखाई दे रही है।', bn: 'আপনার চাকরি এখন লাইভ এবং প্রার্থীদের কাছে দৃশ্যমান।' },
  'wizard.jobPendingApproval': { en: 'Your job will be visible once approved by our team.', hi: 'हमारी टीम द्वारा अनुमोदित होने के बाद आपकी नौकरी दिखाई देगी।', bn: 'আমাদের দল অনুমোদন করলে আপনার চাকরি দৃশ্যমান হবে।' },
  'wizard.postingJob': { en: 'Posting Job...', hi: 'नौकरी पोस्ट हो रही है...', bn: 'চাকরি পোস্ট হচ্ছে...' },

  // Job Details Step
  'jobDetails.title': { en: 'Job details', hi: 'नौकरी विवरण', bn: 'চাকরির বিবরণ' },
  'jobDetails.desc': { en: 'We use this information to find the best candidates for the job.', hi: 'हम इस जानकारी का उपयोग नौकरी के लिए सर्वश्रेष्ठ उम्मीदवारों को खोजने के लिए करते हैं।', bn: 'আমরা এই তথ্য ব্যবহার করি চাকরির জন্য সেরা প্রার্থী খুঁজতে।' },
  'jobDetails.mandatory': { en: '*Marked fields are mandatory', hi: '*चिह्नित फ़ील्ड अनिवार्य हैं', bn: '*চিহ্নিত ক্ষেত্রগুলি বাধ্যতামূলক' },
  'jobDetails.companyHiring': { en: "Company you're hiring for", hi: 'जिस कंपनी के लिए भर्ती कर रहे हैं', bn: 'যে কোম্পানির জন্য নিয়োগ করছেন' },
  'jobDetails.change': { en: 'Change', hi: 'बदलें', bn: 'পরিবর্তন করুন' },
  'jobDetails.jobTitle': { en: 'Job title / Designation', hi: 'नौकरी शीर्षक / पदनाम', bn: 'চাকরির শিরোনাম / পদবী' },
  'jobDetails.jobTitlePlaceholder': { en: 'e.g., Senior Software Engineer', hi: 'उदा., सीनियर सॉफ्टवेयर इंजीनियर', bn: 'যেমন, সিনিয়র সফটওয়্যার ইঞ্জিনিয়ার' },
  'jobDetails.jobTitleRequired': { en: 'Job title is required', hi: 'नौकरी शीर्षक आवश्यक है', bn: 'চাকরির শিরোনাম প্রয়োজন' },
  'jobDetails.jobCategory': { en: 'Job Role/Category', hi: 'नौकरी भूमिका/श्रेणी', bn: 'চাকরির ভূমিকা/বিভাগ' },
  'jobDetails.selectCategory': { en: 'Select category', hi: 'श्रेणी चुनें', bn: 'বিভাগ নির্বাচন করুন' },
  'jobDetails.categoryRequired': { en: 'Job category is required', hi: 'नौकरी श्रेणी आवश्यक है', bn: 'চাকরির বিভাগ প্রয়োজন' },
  'jobDetails.jobType': { en: 'Type of Job', hi: 'नौकरी का प्रकार', bn: 'চাকরির ধরন' },
  'jobDetails.nightShift': { en: 'This is a night shift job', hi: 'यह नाइट शिफ्ट की नौकरी है', bn: 'এটি একটি নাইট শিফট চাকরি' },
  'jobDetails.location': { en: 'Location', hi: 'स्थान', bn: 'অবস্থান' },
  'jobDetails.locationDesc': { en: 'Let candidates know where they will be working from.', hi: 'उम्मीदवारों को बताएं कि वे कहां से काम करेंगे।', bn: 'প্রার্থীদের জানান তারা কোথা থেকে কাজ করবে।' },
  'jobDetails.workLocationType': { en: 'Work location type', hi: 'कार्य स्थान प्रकार', bn: 'কাজের অবস্থানের ধরন' },
  'jobDetails.workFromOffice': { en: 'Work From Office', hi: 'ऑफिस से काम', bn: 'অফিস থেকে কাজ' },
  'jobDetails.workFromHome': { en: 'Work From Home', hi: 'घर से काम', bn: 'বাড়ি থেকে কাজ' },
  'jobDetails.hybrid': { en: 'Hybrid', hi: 'हाइब्रिड', bn: 'হাইব্রিড' },
  'jobDetails.remote': { en: 'Remote', hi: 'रिमोट', bn: 'দূরবর্তী' },
  'jobDetails.jobCity': { en: 'Job City', hi: 'नौकरी का शहर', bn: 'চাকরির শহর' },
  'jobDetails.selectCity': { en: 'Select city', hi: 'शहर चुनें', bn: 'শহর নির্বাচন করুন' },
  'jobDetails.cityRequired': { en: 'City is required', hi: 'शहर आवश्यक है', bn: 'শহর প্রয়োজন' },
  'jobDetails.applicationCap': { en: 'Your job will receive a maximum of 250 applications from {city} or remain live for 15 days, whichever comes first.', hi: 'आपकी नौकरी को {city} से अधिकतम 250 आवेदन प्राप्त होंगे या 15 दिनों तक लाइव रहेगी, जो भी पहले हो।', bn: 'আপনার চাকরি {city} থেকে সর্বাধিক 250 আবেদন পাবে অথবা 15 দিন লাইভ থাকবে, যেটি আগে হবে।' },
  'jobDetails.compensation': { en: 'Compensation', hi: 'मुआवजा', bn: 'ক্ষতিপূরণ' },
  'jobDetails.compensationDesc': { en: 'Job postings with right salary & incentives will help you find the right candidates.', hi: 'सही वेतन और प्रोत्साहन के साथ नौकरी पोस्टिंग आपको सही उम्मीदवार खोजने में मदद करेगी।', bn: 'সঠিক বেতন এবং ইনসেনটিভ সহ চাকরির পোস্টিং আপনাকে সঠিক প্রার্থী খুঁজে পেতে সাহায্য করবে।' },
  'jobDetails.payType': { en: 'What is the pay type?', hi: 'वेतन का प्रकार क्या है?', bn: 'বেতনের ধরন কী?' },
  'jobDetails.fixedOnly': { en: 'Fixed Only', hi: 'केवल निश्चित', bn: 'শুধুমাত্র স্থির' },
  'jobDetails.fixedIncentive': { en: 'Fixed + Incentive', hi: 'निश्चित + प्रोत्साहन', bn: 'স্থির + ইনসেনটিভ' },
  'jobDetails.incentiveOnly': { en: 'Incentive Only', hi: 'केवल प्रोत्साहन', bn: 'শুধুমাত্র ইনসেনটিভ' },
  'jobDetails.fixedSalary': { en: 'Fixed salary / month (excluding incentives)', hi: 'निश्चित वेतन / माह (प्रोत्साहन को छोड़कर)', bn: 'স্থির বেতন / মাস (ইনসেনটিভ ছাড়া)' },
  'jobDetails.avgIncentive': { en: 'Average Incentive / month', hi: 'औसत प्रोत्साहन / माह', bn: 'গড় ইনসেনটিভ / মাস' },
  'jobDetails.salaryBreakup': { en: 'Salary breakup shown to candidates', hi: 'उम्मीदवारों को दिखाया गया वेतन विवरण', bn: 'প্রার্থীদের কাছে দেখানো বেতন বিবরণ' },
  'jobDetails.fixedSalaryMonth': { en: 'Fixed Salary / Month', hi: 'निश्चित वेतन / माह', bn: 'স্থির বেতন / মাস' },
  'jobDetails.avgIncentiveMonth': { en: 'Average Incentive / Month', hi: 'औसत प्रोत्साहन / माह', bn: 'গড় ইনসেনটিভ / মাস' },
  'jobDetails.earningPotential': { en: 'Earning Potential / Month', hi: 'कमाई की संभावना / माह', bn: 'উপার্জন সম্ভাবনা / মাস' },
  'jobDetails.salaryRequired': { en: 'Salary range is required', hi: 'वेतन सीमा आवश्यक है', bn: 'বেতন পরিসীমা প্রয়োজন' },
  'jobDetails.additionalPerks': { en: 'Do you offer any additional perks?', hi: 'क्या आप कोई अतिरिक्त लाभ प्रदान करते हैं?', bn: 'আপনি কি অতিরিক্ত সুবিধা প্রদান করেন?' },
  'jobDetails.joiningFee': { en: 'Is there any joining fee or deposit required from the candidate?', hi: 'क्या उम्मीदवार से कोई ज्वाइनिंग फीस या जमा आवश्यक है?', bn: 'প্রার্থীর কাছ থেকে কোন জয়েনিং ফি বা ডিপোজিট প্রয়োজন?' },
  'jobDetails.yes': { en: 'Yes', hi: 'हां', bn: 'হ্যাঁ' },
  'jobDetails.no': { en: 'No', hi: 'नहीं', bn: 'না' },
  'jobDetails.jobDescription': { en: 'Job Description', hi: 'नौकरी विवरण', bn: 'চাকরির বিবরণ' },
  'jobDetails.describeRole': { en: 'Describe the role and what the candidate will be doing', hi: 'भूमिका और उम्मीदवार क्या करेगा, इसका वर्णन करें', bn: 'ভূমিকা এবং প্রার্থী কী করবে তা বর্ণনা করুন' },
  'jobDetails.writePlaceholder': { en: 'Write a detailed job description...', hi: 'एक विस्तृत नौकरी विवरण लिखें...', bn: 'একটি বিস্তারিত চাকরির বিবরণ লিখুন...' },
  'jobDetails.descriptionRequired': { en: 'Job description is required', hi: 'नौकरी विवरण आवश्यक है', bn: 'চাকরির বিবরণ প্রয়োজন' },

  // Candidate Requirements Step
  'candidateReq.eligibleTitle': { en: 'Eligible requirements', hi: 'पात्रता आवश्यकताएं', bn: 'যোগ্যতার প্রয়োজনীয়তা' },
  'candidateReq.eligibleDesc': { en: 'Your job will only be visible to the candidates who meet these requirements.', hi: 'आपकी नौकरी केवल उन उम्मीदवारों को दिखाई देगी जो इन आवश्यकताओं को पूरा करते हैं।', bn: 'আপনার চাকরি শুধুমাত্র সেই প্রার্থীদের কাছে দৃশ্যমান হবে যারা এই প্রয়োজনীয়তা পূরণ করে।' },
  'candidateReq.minEducation': { en: 'Minimum Education', hi: 'न्यूनतम शिक्षा', bn: 'সর্বনিম্ন শিক্ষা' },
  'candidateReq.selectMinEducation': { en: 'Select minimum education', hi: 'न्यूनतम शिक्षा चुनें', bn: 'সর্বনিম্ন শিক্ষা নির্বাচন করুন' },
  'candidateReq.experienceRequired': { en: 'Experience Required', hi: 'आवश्यक अनुभव', bn: 'প্রয়োজনীয় অভিজ্ঞতা' },
  'candidateReq.selectExperience': { en: 'Select experience level', hi: 'अनुभव स्तर चुनें', bn: 'অভিজ্ঞতার স্তর নির্বাচন করুন' },
  'candidateReq.englishProficiency': { en: 'English Proficiency', hi: 'अंग्रेजी दक्षता', bn: 'ইংরেজি দক্ষতা' },
  'candidateReq.selectEnglish': { en: 'Select English level', hi: 'अंग्रेजी स्तर चुनें', bn: 'ইংরেজি স্তর নির্বাচন করুন' },
  'candidateReq.preferredTitle': { en: 'Preferred requirements', hi: 'पसंदीदा आवश्यकताएं', bn: 'পছন্দের প্রয়োজনীয়তা' },
  'candidateReq.preferredDesc': { en: 'Your job will be promoted to the candidates meeting below requirements, but others can still apply.', hi: 'आपकी नौकरी नीचे दी गई आवश्यकताओं को पूरा करने वाले उम्मीदवारों को प्रचारित की जाएगी, लेकिन अन्य अभी भी आवेदन कर सकते हैं।', bn: 'আপনার চাকরি নিম্নলিখিত প্রয়োজনীয়তা পূরণকারী প্রার্থীদের কাছে প্রচার করা হবে, তবে অন্যরাও আবেদন করতে পারবে।' },
  'candidateReq.ageRange': { en: 'Age Range', hi: 'आयु सीमा', bn: 'বয়স সীমা' },
  'candidateReq.yrs': { en: 'yrs', hi: 'वर्ष', bn: 'বছর' },
  'candidateReq.to': { en: 'to', hi: 'से', bn: 'থেকে' },
  'candidateReq.genderPreference': { en: 'Gender Preference', hi: 'लिंग वरीयता', bn: 'লিঙ্গ পছন্দ' },
  'candidateReq.bothGenders': { en: 'Both genders allowed', hi: 'दोनों लिंग स्वीकार्य', bn: 'উভয় লিঙ্গ অনুমোদিত' },
  'candidateReq.maleOnly': { en: 'Male only', hi: 'केवल पुरुष', bn: 'শুধুমাত্র পুরুষ' },
  'candidateReq.femaleOnly': { en: 'Female only', hi: 'केवल महिला', bn: 'শুধুমাত্র মহিলা' },
  'candidateReq.industryExp': { en: 'Preferred Industry Experience', hi: 'पसंदीदा उद्योग अनुभव', bn: 'পছন্দের শিল্প অভিজ্ঞতা' },
  'candidateReq.selectIndustry': { en: 'Select industry', hi: 'उद्योग चुनें', bn: 'শিল্প নির্বাচন করুন' },
  'candidateReq.requiredSkills': { en: 'Required Skills', hi: 'आवश्यक कौशल', bn: 'প্রয়োজনীয় দক্ষতা' },
  'candidateReq.addSkill': { en: 'Add a skill', hi: 'कौशल जोड़ें', bn: 'দক্ষতা যোগ করুন' },
  'candidateReq.selected': { en: 'Selected:', hi: 'चयनित:', bn: 'নির্বাচিত:' },
  'candidateReq.detailedReq': { en: 'Detailed Requirements & Responsibilities', hi: 'विस्तृत आवश्यकताएं और जिम्मेदारियां', bn: 'বিস্তারিত প্রয়োজনীয়তা এবং দায়িত্ব' },
  'candidateReq.requirements': { en: 'Requirements', hi: 'आवश्यकताएं', bn: 'প্রয়োজনীয়তা' },
  'candidateReq.reqPlaceholder': { en: '- 5+ years of experience\n- Strong communication skills\n- Bachelor\'s degree required', hi: '- 5+ वर्ष का अनुभव\n- मजबूत संचार कौशल\n- स्नातक की डिग्री आवश्यक', bn: '- 5+ বছরের অভিজ্ঞতা\n- শক্তিশালী যোগাযোগ দক্ষতা\n- স্নাতক ডিগ্রি প্রয়োজন' },
  'candidateReq.responsibilities': { en: 'Responsibilities', hi: 'जिम्मेदारियां', bn: 'দায়িত্ব' },
  'candidateReq.respPlaceholder': { en: '- Lead team meetings\n- Manage client relationships\n- Report to senior management', hi: '- टीम मीटिंग्स का नेतृत्व करें\n- क्लाइंट संबंध प्रबंधित करें\n- वरिष्ठ प्रबंधन को रिपोर्ट करें', bn: '- দলের মিটিং নেতৃত্ব দিন\n- ক্লায়েন্ট সম্পর্ক পরিচালনা করুন\n- সিনিয়র ম্যানেজমেন্টকে রিপোর্ট করুন' },

  // Interview Info Step
  'interview.methodTitle': { en: 'Interview method and address', hi: 'साक्षात्कार विधि और पता', bn: 'ইন্টারভিউ পদ্ধতি এবং ঠিকানা' },
  'interview.methodDesc': { en: 'Let candidates know how interview will be conducted for this job.', hi: 'उम्मीदवारों को बताएं कि इस नौकरी के लिए साक्षात्कार कैसे आयोजित किया जाएगा।', bn: 'প্রার্থীদের জানান এই চাকরির জন্য ইন্টারভিউ কীভাবে পরিচালিত হবে।' },
  'interview.isWalkIn': { en: 'Is this a walk-in interview?', hi: 'क्या यह वॉक-इन इंटरव्यू है?', bn: 'এটি কি ওয়াক-ইন ইন্টারভিউ?' },
  'interview.knowMore': { en: 'Know More', hi: 'और जानें', bn: 'আরও জানুন' },
  'interview.companyAddress': { en: 'Company address', hi: 'कंपनी का पता', bn: 'কোম্পানির ঠিকানা' },
  'interview.enterAddress': { en: 'Enter complete company address', hi: 'पूरा कंपनी पता दर्ज करें', bn: 'সম্পূর্ণ কোম্পানির ঠিকানা লিখুন' },
  'interview.useCompanyLocation': { en: 'Use company location:', hi: 'कंपनी स्थान का उपयोग करें:', bn: 'কোম্পানির অবস্থান ব্যবহার করুন:' },
  'interview.commPreference': { en: 'Communication Preferences', hi: 'संचार प्राथमिकताएं', bn: 'যোগাযোগ পছন্দ' },
  'interview.commQuestion': { en: 'Do you want candidates to contact you via Call / Whatsapp after they apply?', hi: 'क्या आप चाहते हैं कि उम्मीदवार आवेदन के बाद कॉल/व्हाट्सएप के माध्यम से आपसे संपर्क करें?', bn: 'আপনি কি চান প্রার্থীরা আবেদনের পরে কল/হোয়াটসঅ্যাপের মাধ্যমে আপনার সাথে যোগাযোগ করুক?' },
  'interview.yesToMyself': { en: 'Yes, to myself', hi: 'हां, मुझे', bn: 'হ্যাঁ, আমাকে' },
  'interview.yesToOther': { en: 'Yes, to other recruiter', hi: 'हां, अन्य रिक्रूटर को', bn: 'হ্যাঁ, অন্য রিক্রুটারকে' },
  'interview.noContact': { en: 'No, I will contact candidates first', hi: 'नहीं, मैं पहले उम्मीदवारों से संपर्क करूंगा', bn: 'না, আমি প্রথমে প্রার্থীদের সাথে যোগাযোগ করব' },
  'interview.recruiterPhone': { en: 'Recruiter Phone Number', hi: 'रिक्रूटर फोन नंबर', bn: 'রিক্রুটার ফোন নম্বর' },
  'interview.notifPreference': { en: 'Notification Preferences', hi: 'सूचना प्राथमिकताएं', bn: 'বিজ্ঞপ্তি পছন্দ' },
  'interview.notifQuestion': { en: 'Every time you receive a matched candidate application, do you want Email Alerts from TrueJobs?', hi: 'जब भी आपको मिलान उम्मीदवार आवेदन प्राप्त होता है, क्या आप TrueJobs से ईमेल अलर्ट चाहते हैं?', bn: 'প্রতিবার মিলিত প্রার্থী আবেদন পেলে, আপনি কি TrueJobs থেকে ইমেল সতর্কতা চান?' },
  'interview.emailMyself': { en: 'Yes, to myself', hi: 'हां, मुझे', bn: 'হ্যাঁ, আমাকে' },
  'interview.emailOther': { en: 'Yes, to other recruiter', hi: 'हां, अन्य रिक्रूटर को', bn: 'হ্যাঁ, অন্য রিক্রুটারকে' },
  'interview.dailySummary': { en: 'No, send me summary once a day', hi: 'नहीं, मुझे दिन में एक बार सारांश भेजें', bn: 'না, আমাকে দিনে একবার সারাংশ পাঠান' },
  'interview.new': { en: 'New', hi: 'नया', bn: 'নতুন' },

  // Job Preview Step
  'preview.jobDetails': { en: 'Job Details', hi: 'नौकरी विवरण', bn: 'চাকরির বিবরণ' },
  'preview.companyName': { en: 'Company name', hi: 'कंपनी का नाम', bn: 'কোম্পানির নাম' },
  'preview.jobTitle': { en: 'Job title', hi: 'नौकरी शीर्षक', bn: 'চাকরির শিরোনাম' },
  'preview.jobRole': { en: 'Job role/category', hi: 'नौकरी भूमिका/श्रेणी', bn: 'চাকরির ভূমিকা/বিভাগ' },
  'preview.jobType': { en: 'Job type', hi: 'नौकरी का प्रकार', bn: 'চাকরির ধরন' },
  'preview.dayShift': { en: 'Day shift', hi: 'दिन की पाली', bn: 'দিনের শিফট' },
  'preview.nightShift': { en: 'Night shift', hi: 'रात की पाली', bn: 'রাতের শিফট' },
  'preview.workType': { en: 'Work type', hi: 'कार्य प्रकार', bn: 'কাজের ধরন' },
  'preview.jobCity': { en: 'Job City', hi: 'नौकरी का शहर', bn: 'চাকরির শহর' },
  'preview.applicationCap': { en: 'Your job will receive a maximum of 250 applications from {city} or remain live for 15 days, whichever comes first.', hi: 'आपकी नौकरी को {city} से अधिकतम 250 आवेदन प्राप्त होंगे या 15 दिनों तक लाइव रहेगी, जो भी पहले हो।', bn: 'আপনার চাকরি {city} থেকে সর্বাধিক 250 আবেদন পাবে অথবা 15 দিন লাইভ থাকবে, যেটি আগে হবে।' },
  'preview.monthlySalary': { en: 'Monthly Salary | Pay Type', hi: 'मासिक वेतन | वेतन प्रकार', bn: 'মাসিক বেতন | বেতনের ধরন' },
  'preview.perMonth': { en: 'per month', hi: 'प्रति माह', bn: 'প্রতি মাসে' },
  'preview.fixed': { en: 'Fixed', hi: 'निश्चित', bn: 'স্থির' },
  'preview.fixedPlusIncentives': { en: 'Fixed + Incentives', hi: 'निश्चित + प्रोत्साहन', bn: 'স্থির + ইনসেনটিভ' },
  'preview.incentiveOnlyLabel': { en: 'Incentive only', hi: 'केवल प्रोत्साहन', bn: 'শুধুমাত্র ইনসেনটিভ' },
  'preview.additionalPerks': { en: 'Additional perks', hi: 'अतिरिक्त लाभ', bn: 'অতিরিক্ত সুবিধা' },
  'preview.none': { en: 'None', hi: 'कोई नहीं', bn: 'কোনটি নয়' },
  'preview.joiningFee': { en: 'Joining Fee', hi: 'ज्वाइनिंग फीस', bn: 'জয়েনিং ফি' },
  'preview.candidateReq': { en: 'Candidate Requirements', hi: 'उम्मीदवार आवश्यकताएं', bn: 'প্রার্থীর প্রয়োজনীয়তা' },
  'preview.eligibleReq': { en: 'Eligible requirements', hi: 'पात्रता आवश्यकताएं', bn: 'যোগ্যতার প্রয়োজনীয়তা' },
  'preview.eligibleDesc': { en: 'Your job will only be visible to the candidates who meet these requirements.', hi: 'आपकी नौकरी केवल उन उम्मीदवारों को दिखाई देगी जो इन आवश्यकताओं को पूरा करते हैं।', bn: 'আপনার চাকরি শুধুমাত্র সেই প্রার্থীদের কাছে দৃশ্যমান হবে যারা এই প্রয়োজনীয়তা পূরণ করে।' },
  'preview.minEducation': { en: 'Minimum Education', hi: 'न्यूनतम शिक्षा', bn: 'সর্বনিম্ন শিক্ষা' },
  'preview.notSpecified': { en: 'Not specified', hi: 'निर्दिष्ट नहीं', bn: 'নির্দিষ্ট নয়' },
  'preview.expRequired': { en: 'Experience Required', hi: 'आवश्यक अनुभव', bn: 'প্রয়োজনীয় অভিজ্ঞতা' },
  'preview.english': { en: 'English', hi: 'अंग्रेजी', bn: 'ইংরেজি' },
  'preview.preferredReq': { en: 'Preferred requirements', hi: 'पसंदीदा आवश्यकताएं', bn: 'পছন্দের প্রয়োজনীয়তা' },
  'preview.preferredDesc': { en: 'Your job will be promoted to the candidates meeting below requirements, but others can still apply.', hi: 'आपकी नौकरी नीचे दी गई आवश्यकताओं को पूरा करने वाले उम्मीदवारों को प्रचारित की जाएगी, लेकिन अन्य अभी भी आवेदन कर सकते हैं।', bn: 'আপনার চাকরি নিম্নলিখিত প্রয়োজনীয়তা পূরণকারী প্রার্থীদের কাছে প্রচার করা হবে, তবে অন্যরাও আবেদন করতে পারবে।' },
  'preview.age': { en: 'Age', hi: 'आयु', bn: 'বয়স' },
  'preview.gender': { en: 'Gender', hi: 'लिंग', bn: 'লিঙ্গ' },
  'preview.industry': { en: 'Industry', hi: 'उद्योग', bn: 'শিল্প' },
  'preview.skills': { en: 'Skills', hi: 'कौशल', bn: 'দক্ষতা' },
  'preview.noneSpecified': { en: 'None specified', hi: 'कोई निर्दिष्ट नहीं', bn: 'কোনটি নির্দিষ্ট নেই' },
  'preview.jobDesc': { en: 'Job Description', hi: 'नौकरी विवरण', bn: 'চাকরির বিবরণ' },
  'preview.viewFullDesc': { en: 'View full description', hi: 'पूर्ण विवरण देखें', bn: 'সম্পূর্ণ বিবরণ দেখুন' },
  'preview.interviewInfo': { en: 'Interview Information', hi: 'साक्षात्कार जानकारी', bn: 'ইন্টারভিউ তথ্য' },
  'preview.commPreference': { en: 'Communication Preference:', hi: 'संचार प्राथमिकता:', bn: 'যোগাযোগ পছন্দ:' },
  'preview.myself': { en: 'Myself', hi: 'स्वयं', bn: 'নিজে' },
  'preview.otherRecruiter': { en: 'Other recruiter', hi: 'अन्य रिक्रूटर', bn: 'অন্য রিক্রুটার' },
  'preview.willContact': { en: 'Will contact candidates', hi: 'उम्मीदवारों से संपर्क करेंगे', bn: 'প্রার্থীদের সাথে যোগাযোগ করবে' },
  'preview.walkInQuestion': { en: 'Is this walk-in interview?', hi: 'क्या यह वॉक-इन इंटरव्यू है?', bn: 'এটি কি ওয়াক-ইন ইন্টারভিউ?' },
  'preview.notProvided': { en: 'Not provided', hi: 'प्रदान नहीं किया गया', bn: 'প্রদান করা হয়নি' },
  'preview.notifPreference': { en: 'Notification Preference', hi: 'सूचना प्राथमिकता', bn: 'বিজ্ঞপ্তি পছন্দ' },
  'preview.emailToMyself': { en: 'Email to myself', hi: 'ईमेल मुझे', bn: 'ইমেল আমাকে' },
  'preview.emailToOther': { en: 'Email to other recruiter', hi: 'ईमेल अन्य रिक्रूटर को', bn: 'ইমেল অন্য রিক্রুটারকে' },
  'preview.dailySummaryLabel': { en: 'Daily summary', hi: 'दैनिक सारांश', bn: 'দৈনিক সারাংশ' },

  // Plan Selection Step
  'plan.title': { en: 'Choose a plan based on your hiring needs', hi: 'अपनी भर्ती आवश्यकताओं के आधार पर एक योजना चुनें', bn: 'আপনার নিয়োগ প্রয়োজনের উপর ভিত্তি করে একটি পরিকল্পনা নির্বাচন করুন' },
  'plan.introducingAI': { en: 'Introducing AI Agent', hi: 'AI एजेंट पेश है', bn: 'AI এজেন্ট পরিচিতি' },
  'plan.aiAgent': { en: '+ AI Agent', hi: '+ AI एजेंट', bn: '+ AI এজেন্ট' },
  'plan.off': { en: 'OFF', hi: 'छूट', bn: 'ছাড়' },
  'plan.emailNotif': { en: 'Email notifications to top candidates', hi: 'शीर्ष उम्मीदवारों को ईमेल सूचनाएं', bn: 'শীর্ষ প্রার্থীদের ইমেল বিজ্ঞপ্তি' },
  'plan.urgentlyHiring': { en: "Featured with 'Urgently hiring' tag", hi: "'तत्काल भर्ती' टैग के साथ फीचर्ड", bn: "'জরুরি নিয়োগ' ট্যাগ সহ বৈশিষ্ট্যযুক্ত" },
  'plan.topPlacements': { en: 'Top placements in job listings', hi: 'नौकरी लिस्टिंग में शीर्ष प्लेसमेंट', bn: 'চাকরির তালিকায় শীর্ষ স্থান' },
  'plan.excludingTax': { en: '*All prices are excluding taxes.', hi: '*सभी कीमतों में कर शामिल नहीं है।', bn: '*সমস্ত মূল্য কর ব্যতীত।' },
  'plan.trustedBy': { en: 'Trusted by 1000+ enterprises and 7 lakh+ MSMEs for hiring', hi: '1000+ उद्यमों और 7 लाख+ MSMEs द्वारा भर्ती के लिए विश्वसनीय', bn: 'নিয়োগের জন্য 1000+ এন্টারপ্রাইজ এবং 7 লাখ+ MSME দ্বারা বিশ্বস্ত' },

  // Hero Section Extended
  'hero.trustedBy': { en: 'Leading Companies', hi: 'प्रमुख कंपनियाँ', bn: 'নেতৃস্থানীয় কোম্পানি' },
  'hero.benefit1': { en: 'AI-powered job matching', hi: 'AI-संचालित जॉब मिलान', bn: 'AI-চালিত চাকরি ম্যাচিং' },
  'hero.benefit2': { en: 'One-click easy apply', hi: 'एक क्लिक आसान आवेदन', bn: 'এক ক্লিকে সহজ আবেদন' },
  'hero.benefit3': { en: 'AI Free resume builder', hi: 'AI मुफ्त रिज्यूमे बिल्डर', bn: 'AI বিনামূল্যে জীবনবৃত্তান্ত নির্মাতা' },
  'hero.newJobsToday': { en: '500+ new jobs today', hi: 'आज 500+ नई नौकरियाँ', bn: 'আজ 500+ নতুন চাকরি' },

  // Job Categories
  'categories.title': { en: 'Popular Job Categories', hi: 'लोकप्रिय नौकरी श्रेणियाँ', bn: 'জনপ্রিয় চাকরির বিভাগ' },
  'categories.subtitle': { en: 'Explore opportunities that match your interests', hi: 'अपनी रुचियों से मेल खाते अवसर खोजें', bn: 'আপনার আগ্রহের সাথে মেলে এমন সুযোগ অন্বেষণ করুন' },
  'categories.freshers': { en: 'Jobs for Freshers', hi: 'फ्रेशर्स के लिए नौकरियाँ', bn: 'নবাগতদের জন্য চাকরি' },
  'categories.workFromHome': { en: 'Work From Home', hi: 'घर से काम', bn: 'বাড়ি থেকে কাজ' },
  'categories.partTime': { en: 'Part Time Jobs', hi: 'पार्ट टाइम नौकरियाँ', bn: 'খণ্ডকালীন চাকরি' },
  'categories.fullTime': { en: 'Full Time Jobs', hi: 'फुल टाइम नौकरियाँ', bn: 'পূর্ণকালীন চাকরি' },
  'categories.forWomen': { en: 'Jobs for Women', hi: 'महिलाओं के लिए नौकरियाँ', bn: 'মহিলাদের জন্য চাকরি' },
  'categories.internship': { en: 'Internships', hi: 'इंटर्नशिप', bn: 'ইন্টার্নশিপ' },

  // Free Training Section
  'training.badge': { en: 'Free Training', hi: 'मुफ्त प्रशिक्षण', bn: 'বিনামূল্যে প্রশিক্ষণ' },
  'training.title': { en: 'Free Online Training', hi: 'मुफ्त ऑनलाइन प्रशिक्षण', bn: 'বিনামূল্যে অনলাইন প্রশিক্ষণ' },
  'training.subtitle': { en: 'Upskill yourself with our free courses and get job-ready', hi: 'हमारे मुफ्त कोर्स के साथ खुद को अपस्किल करें और जॉब-रेडी बनें', bn: 'আমাদের বিনামূল্যে কোর্সের মাধ্যমে নিজেকে আপস্কিল করুন এবং চাকরির জন্য প্রস্তুত হন' },
  'training.feature1': { en: 'Self-paced learning modules', hi: 'स्व-गति सीखने के मॉड्यूल', bn: 'স্ব-গতির শেখার মডিউল' },
  'training.feature2': { en: 'Video tutorials by experts', hi: 'विशेषज्ञों द्वारा वीडियो ट्यूटोरियल', bn: 'বিশেষজ্ঞদের ভিডিও টিউটোরিয়াল' },
  'training.feature3': { en: 'Industry-recognized certificates', hi: 'उद्योग-मान्यता प्राप्त प्रमाणपत्र', bn: 'ইন্ডাস্ট্রি-স্বীকৃত সার্টিফিকেট' },
  'training.cta': { en: 'Start Learning Free', hi: 'मुफ्त सीखना शुरू करें', bn: 'বিনামূল্যে শেখা শুরু করুন' },
  'training.whyTitle': { en: 'Why Learn With Us?', hi: 'हमारे साथ क्यों सीखें?', bn: 'আমাদের সাথে কেন শিখবেন?' },
  'training.whySubtitle': { en: 'Get ahead in your career with practical skills', hi: 'व्यावहारिक कौशल के साथ अपने करियर में आगे बढ़ें', bn: 'ব্যবহারিক দক্ষতার সাথে আপনার ক্যারিয়ারে এগিয়ে যান' },
  'training.benefit1Title': { en: 'Practical Skills', hi: 'व्यावहारिक कौशल', bn: 'ব্যবহারিক দক্ষতা' },
  'training.benefit1Desc': { en: 'Learn job-relevant skills that employers actually need', hi: 'ऐसे जॉब-संबंधित कौशल सीखें जिनकी नियोक्ताओं को वास्तव में जरूरत है', bn: 'নিয়োগকর্তাদের প্রকৃতপক্ষে প্রয়োজন এমন চাকরি-প্রাসঙ্গিক দক্ষতা শিখুন' },
  'training.benefit2Title': { en: 'Career Guidance', hi: 'करियर मार्गदर्शन', bn: 'ক্যারিয়ার গাইডেন্স' },
  'training.benefit2Desc': { en: 'Get personalized career advice from industry mentors', hi: 'उद्योग के मेंटर्स से व्यक्तिगत करियर सलाह प्राप्त करें', bn: 'ইন্ডাস্ট্রি মেন্টরদের কাছ থেকে ব্যক্তিগত ক্যারিয়ার পরামর্শ পান' },
  'training.benefit3Title': { en: 'Get Certified', hi: 'प्रमाणित हों', bn: 'সার্টিফাইড হন' },
  'training.benefit3Desc': { en: 'Earn certificates to boost your resume and stand out', hi: 'अपना रिज्यूमे बढ़ाने और अलग दिखने के लिए प्रमाणपत्र अर्जित करें', bn: 'আপনার জীবনবৃত্তান্ত বাড়াতে এবং আলাদা হতে সার্টিফিকেট অর্জন করুন' },

  // Top Companies
  'topCompanies.title': { en: 'Job Openings in Top Companies', hi: 'शीर्ष कंपनियों में नौकरी के अवसर', bn: 'শীর্ষ কোম্পানিতে চাকরির সুযোগ' },
  'topCompanies.subtitle': { en: 'Discover opportunities from industry leaders', hi: 'उद्योग के अग्रणी कंपनियों से अवसर खोजें', bn: 'ইন্ডাস্ট্রি লিডারদের থেকে সুযোগ আবিষ্কার করুন' },
  'topCompanies.viewAll': { en: 'View All Companies', hi: 'सभी कंपनियाँ देखें', bn: 'সব কোম্পানি দেখুন' },
  'topCompanies.viewJobs': { en: 'View Jobs', hi: 'नौकरियाँ देखें', bn: 'চাকরি দেখুন' },

  // Trending Roles
  'trendingRoles.badge': { en: 'In-demand roles this week', hi: 'इस सप्ताह की मांग वाली भूमिकाएं', bn: 'এই সপ্তাহে চাহিদার ভূমিকা' },
  'trendingRoles.title': { en: 'Trending Job Roles', hi: 'ट्रेंडिंग नौकरी भूमिकाएं', bn: 'ট্রেন্ডিং চাকরির ভূমিকা' },
  'trendingRoles.subtitle': { en: 'Explore the most in-demand roles across industries', hi: 'उद्योगों में सबसे अधिक मांग वाली भूमिकाओं का अन्वेषण करें', bn: 'শিল্প জুড়ে সর্বাধিক চাহিদাপূর্ণ ভূমিকা অন্বেষণ করুন' },
  'trendingRoles.viewAll': { en: 'View all job roles', hi: 'सभी नौकरी भूमिकाएं देखें', bn: 'সমস্ত চাকরির ভূমিকা দেখুন' },
  'trendingRoles.salesMarketing': { en: 'Sales & Marketing', hi: 'बिक्री और विपणन', bn: 'বিক্রয় ও বিপণন' },
  'trendingRoles.operationsDelivery': { en: 'Operations & Delivery', hi: 'संचालन और डिलीवरी', bn: 'অপারেশন ও ডেলিভারি' },
  'trendingRoles.financeHR': { en: 'Finance & HR', hi: 'वित्त और एचआर', bn: 'ফিনান্স ও এইচআর' },
  'trendingRoles.itCreative': { en: 'IT & Creative', hi: 'आईटी और क्रिएटिव', bn: 'আইটি ও ক্রিয়েটিভ' },
  'trendingRoles.education': { en: 'Education', hi: 'शिक्षा', bn: 'শিক্ষা' },

  // Testimonials
  'testimonials.title': { en: 'Trusted by Job Seekers and Employers Across India', hi: 'पूरे भारत में नौकरी चाहने वालों और नियोक्ताओं द्वारा विश्वसनीय', bn: 'সারা ভারতে চাকরি প্রার্থী ও নিয়োগকর্তাদের দ্বারা বিশ্বস্ত' },
  'testimonials.subtitle': { en: 'Real placement outcomes and hiring success from verified users', hi: 'सत्यापित उपयोगकर्ताओं से वास्तविक प्लेसमेंट परिणाम और भर्ती सफलता', bn: 'যাচাইকৃত ব্যবহারকারীদের থেকে প্রকৃত প্লেসমেন্ট ফলাফল এবং নিয়োগ সাফল্য' },
  'testimonials.ratingText': { en: 'from 10,000+ users', hi: '10,000+ उपयोगकर्ताओं से', bn: '10,000+ ব্যবহারকারী থেকে' },
  'testimonials.text1': { en: 'Got placed at a reputed IT company within 3 weeks. The application process was smooth and I received interview calls quickly.', hi: '3 सप्ताह में एक प्रतिष्ठित IT कंपनी में प्लेसमेंट मिली। आवेदन प्रक्रिया सुचारू थी और मुझे जल्दी इंटरव्यू कॉल मिले।', bn: '3 সপ্তাহের মধ্যে একটি স্বনামধন্য IT কোম্পানিতে প্লেসমেন্ট পেয়েছি। আবেদন প্রক্রিয়া মসৃণ ছিল এবং দ্রুত ইন্টারভিউ কল পেয়েছি।' },
  'testimonials.textEmployer': { en: 'Closed 12 positions in one quarter. The candidate quality and response rate exceeded our expectations.', hi: 'एक तिमाही में 12 पदों को भरा। उम्मीदवार गुणवत्ता और प्रतिक्रिया दर हमारी उम्मीदों से अधिक थी।', bn: 'এক প্রান্তিকে 12টি পদ পূরণ করেছি। প্রার্থীর মান এবং প্রতিক্রিয়ার হার আমাদের প্রত্যাশা ছাড়িয়ে গেছে।' },
  'testimonials.text3': { en: 'As a fresher, I found genuine opportunities without any registration fees. Got my first job through this platform.', hi: 'एक फ्रेशर के रूप में, मुझे बिना किसी पंजीकरण शुल्क के वास्तविक अवसर मिले। इस प्लेटफॉर्म के माध्यम से पहली नौकरी मिली।', bn: 'নবাগত হিসেবে, কোনো রেজিস্ট্রেশন ফি ছাড়াই আসল সুযোগ পেয়েছি। এই প্ল্যাটফর্মের মাধ্যমে প্রথম চাকরি পেয়েছি।' },
  'testimonials.employer': { en: 'Employer', hi: 'नियोक्ता', bn: 'নিয়োগকর্তা' },
  'testimonials.candidate': { en: 'Candidate', hi: 'उम्मीदवार', bn: 'প্রার্থী' },
  'testimonials.trustedBy': { en: 'Hiring Companies across India', hi: 'पूरे भारत में भर्ती कंपनियाँ', bn: 'সারা ভারতে নিয়োগকারী কোম্পানি' },
  'testimonials.stat.placements': { en: 'Placements', hi: 'प्लेसमेंट', bn: 'প্লেসমেন্ট' },
  'testimonials.stat.employers': { en: 'Employers', hi: 'नियोक्ता', bn: 'নিয়োগকর্তা' },
  'testimonials.stat.rating': { en: 'User Rating', hi: 'उपयोगकर्ता रेटिंग', bn: 'ব্যবহারকারী রেটিং' },

  // Employer CTA
  'employerCTA.badge': { en: 'For Employers', hi: 'नियोक्ताओं के लिए', bn: 'নিয়োগকর্তাদের জন্য' },
  'employerCTA.title': { en: 'Want to Hire?', hi: 'भर्ती करना चाहते हैं?', bn: 'নিয়োগ করতে চান?' },
  'employerCTA.subtitle': { en: 'Find the best candidates from our pool of verified job seekers', hi: 'हमारे सत्यापित नौकरी चाहने वालों के पूल से सर्वश्रेष्ठ उम्मीदवार खोजें', bn: 'আমাদের যাচাইকৃত চাকরি প্রার্থীদের পুল থেকে সেরা প্রার্থী খুঁজুন' },
  'employerCTA.benefit1': { en: 'Access to 1L+ candidates', hi: '1L+ उम्मीदवारों तक पहुंच', bn: '1L+ প্রার্থীদের অ্যাক্সেস' },
  'employerCTA.benefit2': { en: 'Quick hiring process', hi: 'त्वरित भर्ती प्रक्रिया', bn: 'দ্রুত নিয়োগ প্রক্রিয়া' },
  'employerCTA.benefit3': { en: 'Verified profiles only', hi: 'केवल सत्यापित प्रोफाइल', bn: 'শুধুমাত্র যাচাইকৃত প্রোফাইল' },
  'employerCTA.cta': { en: 'Post a Job Now', hi: 'अभी नौकरी पोस्ट करें', bn: 'এখনই চাকরি পোস্ট করুন' },

  // Newsletter Section
  'newsletter.title': { en: 'Get Job Alerts Straight to Your Inbox', hi: 'सीधे अपने इनबॉक्स में जॉब अलर्ट प्राप्त करें', bn: 'সরাসরি আপনার ইনবক্সে জব অ্যালার্ট পান' },
  'newsletter.subtitle': { en: 'Subscribe to receive personalized job recommendations and career tips weekly', hi: 'व्यक्तिगत नौकरी सिफारिशें और साप्ताहिक करियर टिप्स प्राप्त करने के लिए सब्सक्राइब करें', bn: 'ব্যক্তিগত চাকরির সুপারিশ এবং সাপ্তাহিক ক্যারিয়ার টিপস পেতে সাবস্ক্রাইব করুন' },
  'newsletter.placeholder': { en: 'Enter your email address', hi: 'अपना ईमेल पता दर्ज करें', bn: 'আপনার ইমেল ঠিকানা লিখুন' },
  'newsletter.subscribe': { en: 'Subscribe', hi: 'सब्सक्राइब करें', bn: 'সাবস্ক্রাইব করুন' },
  'newsletter.subscribed': { en: 'You\'re subscribed!', hi: 'आप सब्सक्राइब हो गए!', bn: 'আপনি সাবস্ক্রাইব করেছেন!' },
  'newsletter.successMessage': { en: 'Successfully subscribed to job alerts!', hi: 'जॉब अलर्ट के लिए सफलतापूर्वक सब्सक्राइब किया!', bn: 'জব অ্যালার্টের জন্য সফলভাবে সাবস্ক্রাইব করেছেন!' },
  'newsletter.feature1': { en: 'Daily job updates', hi: 'दैनिक नौकरी अपडेट', bn: 'দৈনিক চাকরির আপডেট' },
  'newsletter.feature2': { en: 'Career tips & advice', hi: 'करियर टिप्स और सलाह', bn: 'ক্যারিয়ার টিপস ও পরামর্শ' },
  'newsletter.feature3': { en: 'Unsubscribe anytime', hi: 'कभी भी अनसब्सक्राइब करें', bn: 'যেকোনো সময় আনসাবস্ক্রাইব করুন' },

  // App Download Section
  'appDownload.badge': { en: 'Download Our App', hi: 'हमारा ऐप डाउनलोड करें', bn: 'আমাদের অ্যাপ ডাউনলোড করুন' },
  'appDownload.title': { en: 'Get Jobs on the Go', hi: 'चलते-फिरते नौकरी पाएं', bn: 'চলতে চলতে চাকরি পান' },
  'appDownload.subtitle': { en: 'Download our app for a seamless job search experience. Apply to jobs anytime, anywhere with just a tap.', hi: 'सहज नौकरी खोज अनुभव के लिए हमारा ऐप डाउनलोड करें। बस एक टैप से कभी भी, कहीं भी नौकरियों के लिए आवेदन करें।', bn: 'একটি নির্বিঘ্ন চাকরি খোঁজার অভিজ্ঞতার জন্য আমাদের অ্যাপ ডাউনলোড করুন। শুধু একটি ট্যাপে যেকোনো সময়, যেকোনো জায়গায় চাকরিতে আবেদন করুন।' },
  'appDownload.feature1': { en: 'Instant job notifications', hi: 'तुरंत नौकरी सूचनाएं', bn: 'তাৎক্ষণিক চাকরির বিজ্ঞপ্তি' },
  'appDownload.feature2': { en: 'Easy one-tap apply', hi: 'आसान एक-टैप आवेदन', bn: 'সহজ এক-ট্যাপ আবেদন' },
  'appDownload.feature3': { en: 'Track applications in real-time', hi: 'रियल-टाइम में आवेदनों को ट्रैक करें', bn: 'রিয়েল-টাইমে আবেদন ট্র্যাক করুন' },
  'appDownload.feature4': { en: 'Chat directly with employers', hi: 'नियोक्ताओं से सीधे चैट करें', bn: 'নিয়োগকর্তাদের সাথে সরাসরি চ্যাট করুন' },
  'appDownload.downloadOn': { en: 'Download on the', hi: 'इस पर डाउनलोड करें', bn: 'ডাউনলোড করুন' },
  'appDownload.getItOn': { en: 'Get it on', hi: 'इस पर पाएं', bn: 'পান এখানে' },
  'appDownload.downloads': { en: 'Downloads', hi: 'डाउनलोड', bn: 'ডাউনলোড' },
  'appDownload.freeDownload': { en: 'Free Download', hi: 'मुफ्त डाउनलोड', bn: 'বিনামূল্যে ডাউনলোড' },
  'appDownload.instantAlerts': { en: 'Instant Alerts', hi: 'तुरंत अलर्ट', bn: 'তাৎক্ষণিক অ্যালার্ট' },
  'appDownload.installNow': { en: 'Install Now', hi: 'अभी इंस्टॉल करें', bn: 'এখনই ইনস্টল করুন' },
  'appDownload.addToHome': { en: 'Add to Home Screen', hi: 'होम स्क्रीन में जोड़ें', bn: 'হোম স্ক্রিনে যোগ করুন' },
  'appDownload.installed': { en: 'Installed', hi: 'इंस्टॉल हो गया', bn: 'ইনস্টল হয়েছে' },
  'appDownload.openApp': { en: 'Open App', hi: 'ऐप खोलें', bn: 'অ্যাপ খুলুন' },
  'appDownload.installSuccess': { en: 'App installed successfully! Find it on your home screen.', hi: 'ऐप सफलतापूर्वक इंस्टॉल हो गया! इसे अपनी होम स्क्रीन पर खोजें।', bn: 'অ্যাপ সফলভাবে ইনস্টল হয়েছে! আপনার হোম স্ক্রিনে এটি খুঁজুন।' },
  'appDownload.alreadyInstalled': { en: 'App is already installed on your device!', hi: 'ऐप पहले से आपके डिवाइस पर इंस्टॉल है!', bn: 'অ্যাপ ইতিমধ্যে আপনার ডিভাইসে ইনস্টল করা আছে!' },
  'appDownload.iosInstructions': { en: 'Install on iPhone', hi: 'iPhone पर इंस्टॉल करें', bn: 'iPhone এ ইনস্টল করুন' },
  'appDownload.iosSteps': { en: 'Tap the Share button, then select "Add to Home Screen"', hi: 'शेयर बटन पर टैप करें, फिर "होम स्क्रीन में जोड़ें" चुनें', bn: 'শেয়ার বোতামে ট্যাপ করুন, তারপর "হোম স্ক্রিনে যোগ করুন" নির্বাচন করুন' },
  'appDownload.iosShare': { en: 'Use Safari Share', hi: 'Safari शेयर का उपयोग करें', bn: 'Safari শেয়ার ব্যবহার করুন' },
  'appDownload.browserInstructions': { en: 'Use your browser menu to add this app to your home screen', hi: 'इस ऐप को अपनी होम स्क्रीन में जोड़ने के लिए अपने ब्राउज़र मेनू का उपयोग करें', bn: 'এই অ্যাপটি আপনার হোম স্ক্রিনে যোগ করতে আপনার ব্রাউজার মেনু ব্যবহার করুন' },
  'appDownload.installedMessage': { en: 'App is installed on your device', hi: 'ऐप आपके डिवाइस पर इंस्टॉल है', bn: 'অ্যাপ আপনার ডিভাইসে ইনস্টল করা আছে' },

  // Recent Jobs Ticker
  'recentJobs.title': { en: 'Just Posted', hi: 'अभी पोस्ट किया', bn: 'এইমাত্র পোস্ট করা হয়েছে' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    return translation[language];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
