export interface CityConfig {
  city: string;
  slug: string;
  state: string;
  nearbyAreas: string;
  localFlavor: string;
}

export interface StatePageConfig {
  state: string;
  slug: string;
  path: string;
}

export const INSURANCE_STATES: StatePageConfig[] = [
  { state: 'Uttar Pradesh', slug: 'uttar-pradesh', path: '/insurance-advisor-jobs-uttar-pradesh' },
  { state: 'West Bengal', slug: 'west-bengal', path: '/insurance-advisor-jobs-west-bengal' },
  { state: 'Madhya Pradesh', slug: 'madhya-pradesh', path: '/insurance-advisor-jobs-madhya-pradesh' },
  { state: 'Bihar', slug: 'bihar', path: '/insurance-advisor-jobs-bihar' },
];

/** Get all cities for a given state */
export function getCitiesByState(stateName: string): CityConfig[] {
  return INSURANCE_CITIES.filter((c) => c.state === stateName);
}

/** Get N nearby cities from same state, excluding current slug */
export function getNearbyCities(currentSlug: string, stateName: string, count = 8): CityConfig[] {
  return INSURANCE_CITIES.filter((c) => c.state === stateName && c.slug !== currentSlug).slice(0, count);
}

export const INSURANCE_CITIES: CityConfig[] = [
  // ── Uttar Pradesh ──
  {
    city: 'Lucknow',
    slug: 'insurance-advisor-jobs-lucknow',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Lucknow, Barabanki, Sitapur, and Unnao',
    localFlavor: 'the capital city of Uttar Pradesh',
  },
  {
    city: 'Noida',
    slug: 'insurance-advisor-jobs-noida',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Noida, Sector 18, Sector 62, and Noida Extension',
    localFlavor: 'a rapidly growing hub in the NCR region',
  },
  {
    city: 'Greater Noida',
    slug: 'insurance-advisor-jobs-greater-noida',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Greater Noida, Knowledge Park, Pari Chowk, and Dadri',
    localFlavor: 'a fast-developing industrial and educational hub near Delhi NCR',
  },
  {
    city: 'Ghaziabad',
    slug: 'insurance-advisor-jobs-ghaziabad',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Ghaziabad, Indirapuram, Vaishali, and Loni',
    localFlavor: 'one of the largest industrial cities in western Uttar Pradesh',
  },
  {
    city: 'Kanpur',
    slug: 'insurance-advisor-jobs-kanpur',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Kanpur, Unnao, Hamirpur, and Fatehpur',
    localFlavor: 'a major industrial and commercial center of Uttar Pradesh',
  },
  {
    city: 'Agra',
    slug: 'insurance-advisor-jobs-agra',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Agra, Firozabad, Mathura, and Mainpuri',
    localFlavor: 'a historically significant city and tourist destination in UP',
  },
  {
    city: 'Varanasi',
    slug: 'insurance-advisor-jobs-varanasi',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Varanasi, Chandauli, Jaunpur, and Mirzapur',
    localFlavor: 'one of the oldest and most culturally rich cities in India',
  },
  {
    city: 'Prayagraj',
    slug: 'insurance-advisor-jobs-prayagraj',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Prayagraj, Kaushambi, Pratapgarh, and Fatehpur',
    localFlavor: 'a prominent educational and administrative center of Uttar Pradesh',
  },
  {
    city: 'Meerut',
    slug: 'insurance-advisor-jobs-meerut',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Meerut, Hapur, Muzaffarnagar, and Baghpat',
    localFlavor: 'a key city in western UP known for its sports goods and trade industry',
  },
  {
    city: 'Gorakhpur',
    slug: 'insurance-advisor-jobs-gorakhpur',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Gorakhpur, Deoria, Kushinagar, and Maharajganj',
    localFlavor: 'a major city in eastern Uttar Pradesh with growing commercial activity',
  },

  // ── Uttar Pradesh Districts ──
  {
    city: 'Aligarh',
    slug: 'insurance-advisor-jobs-aligarh-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Aligarh, Khair, Atrauli, and Iglas',
    localFlavor: 'a renowned educational and lock manufacturing hub in western Uttar Pradesh',
  },
  {
    city: 'Ambedkar Nagar',
    slug: 'insurance-advisor-jobs-ambedkar-nagar-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Ambedkar Nagar, Akbarpur, Tanda, and Jalalpur',
    localFlavor: 'a growing district in eastern UP known for its weaving and textile industry',
  },
  {
    city: 'Amethi',
    slug: 'insurance-advisor-jobs-amethi-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Amethi, Gauriganj, Musafirkhana, and Tiloi',
    localFlavor: 'a politically significant district with expanding rural commerce in central UP',
  },
  {
    city: 'Amroha',
    slug: 'insurance-advisor-jobs-amroha-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Amroha, Hasanpur, Gajraula, and Dhanaura',
    localFlavor: 'a historic town in western UP known for its pottery and small-scale industries',
  },
  {
    city: 'Auraiya',
    slug: 'insurance-advisor-jobs-auraiya-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Auraiya, Dibiyapur, Achhalda, and Bidhuna',
    localFlavor: 'an emerging district along the Yamuna with growing dairy and agricultural trade',
  },
  {
    city: 'Ayodhya',
    slug: 'insurance-advisor-jobs-ayodhya-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Ayodhya, Faizabad, Rudauli, and Bikapur',
    localFlavor: 'one of the most sacred and historically important cities in India with rapid development',
  },
  {
    city: 'Azamgarh',
    slug: 'insurance-advisor-jobs-azamgarh-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Azamgarh, Phoolpur, Lalganj, and Mehnagar',
    localFlavor: 'a culturally vibrant district in eastern UP known for its literary and educational heritage',
  },
  {
    city: 'Baghpat',
    slug: 'insurance-advisor-jobs-baghpat-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Baghpat, Baraut, Khekra, and Pilana',
    localFlavor: 'a district in the NCR region of western UP with strong agricultural and dairy sectors',
  },
  {
    city: 'Bahraich',
    slug: 'insurance-advisor-jobs-bahraich-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Bahraich, Nanpara, Kaiserganj, and Payagpur',
    localFlavor: 'a border district near Nepal with growing commercial activity and wildlife tourism',
  },
  {
    city: 'Ballia',
    slug: 'insurance-advisor-jobs-ballia-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Ballia, Rasra, Bansdih, and Sikanderpur',
    localFlavor: 'a historic district at the eastern tip of UP known for its freedom movement legacy',
  },
  {
    city: 'Balrampur',
    slug: 'insurance-advisor-jobs-balrampur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Balrampur, Tulsipur, Utraula, and Gaindas Bujurg',
    localFlavor: 'a developing district in northern UP with growing trade and agricultural commerce',
  },
  {
    city: 'Banda',
    slug: 'insurance-advisor-jobs-banda-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Banda, Baberu, Naraini, and Atarra',
    localFlavor: 'a key district in the Bundelkhand region with expanding infrastructure and services',
  },
  {
    city: 'Barabanki',
    slug: 'insurance-advisor-jobs-barabanki-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Barabanki, Fatehpur, Haidergarh, and Nawabganj',
    localFlavor: 'a strategically located district near Lucknow with strong handloom and sugar industries',
  },
  {
    city: 'Bareilly',
    slug: 'insurance-advisor-jobs-bareilly-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Bareilly, Aonla, Faridpur, and Baheri',
    localFlavor: 'a major commercial and furniture manufacturing hub in the Rohilkhand region',
  },
  {
    city: 'Basti',
    slug: 'insurance-advisor-jobs-basti-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Basti, Harraiya, Gaur, and Bhanpur',
    localFlavor: 'a divisional headquarters in eastern UP with growing educational and commercial facilities',
  },
  {
    city: 'Bhadohi',
    slug: 'insurance-advisor-jobs-bhadohi-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Bhadohi, Gyanpur, Aurai, and Suriyawan',
    localFlavor: 'the carpet capital of India with a globally recognized handloom and weaving industry',
  },
  {
    city: 'Bijnor',
    slug: 'insurance-advisor-jobs-bijnor-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Bijnor, Najibabad, Nagina, and Dhampur',
    localFlavor: 'a green and industrious district in northern UP known for sugar and paper mills',
  },
  {
    city: 'Budaun',
    slug: 'insurance-advisor-jobs-budaun-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Budaun, Dataganj, Sahaswan, and Bisauli',
    localFlavor: 'a historically rich district in central UP with significant agricultural production',
  },
  {
    city: 'Bulandshahr',
    slug: 'insurance-advisor-jobs-bulandshahr-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Bulandshahr, Khurja, Sikandrabad, and Gulaothi',
    localFlavor: 'a prominent NCR-adjacent district known for its ceramics industry and dairy farming',
  },
  {
    city: 'Chandauli',
    slug: 'insurance-advisor-jobs-chandauli-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Chandauli, Mughalsarai, Chakia, and Sakaldiha',
    localFlavor: 'a scenic district near Varanasi with growing trade along the Ganga corridor',
  },
  {
    city: 'Chitrakoot',
    slug: 'insurance-advisor-jobs-chitrakoot-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Chitrakoot, Karwi, Manikpur, and Mau',
    localFlavor: 'a spiritually significant pilgrimage center in the Bundelkhand region of UP',
  },
  {
    city: 'Deoria',
    slug: 'insurance-advisor-jobs-deoria-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Deoria, Salempur, Bhatpar Rani, and Rudrapur',
    localFlavor: 'an agricultural powerhouse in eastern UP with strong sugar and rice industries',
  },
  {
    city: 'Etah',
    slug: 'insurance-advisor-jobs-etah-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Etah, Aliganj, Kasganj, and Jalesar',
    localFlavor: 'an emerging commercial district in central western UP with growing market activity',
  },
  {
    city: 'Etawah',
    slug: 'insurance-advisor-jobs-etawah-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Etawah, Bharthana, Jaswantnagar, and Saifai',
    localFlavor: 'a historically notable district on the Yamuna known for wildlife and education',
  },
  {
    city: 'Faizabad',
    slug: 'insurance-advisor-jobs-faizabad-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Faizabad, Ayodhya, Rudauli, and Sohawal',
    localFlavor: 'a historic twin-city with Ayodhya experiencing rapid economic transformation',
  },
  {
    city: 'Farrukhabad',
    slug: 'insurance-advisor-jobs-farrukhabad-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Farrukhabad, Fatehgarh, Kaimganj, and Amritpur',
    localFlavor: 'a twin-city district along the Ganges known for its potato trade and calligraphy heritage',
  },
  {
    city: 'Fatehpur',
    slug: 'insurance-advisor-jobs-fatehpur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Fatehpur, Bindki, Khaga, and Malwan',
    localFlavor: 'a centrally located district between Kanpur and Prayagraj with active trade networks',
  },
  {
    city: 'Firozabad',
    slug: 'insurance-advisor-jobs-firozabad-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Firozabad, Tundla, Shikohabad, and Jasrana',
    localFlavor: 'the glass bangle capital of India with a thriving small-scale manufacturing sector',
  },
  {
    city: 'Gautam Buddha Nagar',
    slug: 'insurance-advisor-jobs-gautam-buddha-nagar-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Noida, Greater Noida, Dadri, and Jewar',
    localFlavor: 'a leading IT and industrial hub in the Delhi NCR with rapid urbanization and growth',
  },
  {
    city: 'Ghazipur',
    slug: 'insurance-advisor-jobs-ghazipur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Ghazipur, Saidpur, Jakhanian, and Zamania',
    localFlavor: 'a Ganges-side district in eastern UP known for its opium factory and carpet weaving',
  },
  {
    city: 'Gonda',
    slug: 'insurance-advisor-jobs-gonda-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Gonda, Nawabganj, Karnailganj, and Colonelganj',
    localFlavor: 'a developing district in the Awadh region with expanding infrastructure and services',
  },
  {
    city: 'Hamirpur',
    slug: 'insurance-advisor-jobs-hamirpur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Hamirpur, Rath, Maudaha, and Sarila',
    localFlavor: 'a Bundelkhand district with growing connectivity and emerging commercial opportunities',
  },
  {
    city: 'Hapur',
    slug: 'insurance-advisor-jobs-hapur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Hapur, Pilkhuwa, Dhaulana, and Garh Mukteshwar',
    localFlavor: 'a fast-growing NCR city known for its grain market and industrial establishments',
  },
  {
    city: 'Hardoi',
    slug: 'insurance-advisor-jobs-hardoi-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Hardoi, Shahabad, Sandila, and Bilgram',
    localFlavor: 'one of the largest districts in UP with extensive agricultural and sugar production',
  },
  {
    city: 'Hathras',
    slug: 'insurance-advisor-jobs-hathras-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Hathras, Sadabad, Sikandra Rao, and Mursan',
    localFlavor: 'a compact district in western UP known for its trade in edible oils and spices',
  },
  {
    city: 'Jalaun',
    slug: 'insurance-advisor-jobs-jalaun-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Jalaun, Orai, Konch, and Kalpi',
    localFlavor: 'a Bundelkhand district with historical forts and growing agri-commerce',
  },
  {
    city: 'Jaunpur',
    slug: 'insurance-advisor-jobs-jaunpur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Jaunpur, Machhli Shahar, Shahganj, and Mariahu',
    localFlavor: 'the City of Sharqi Sultans with rich architectural heritage and educational institutions',
  },
  {
    city: 'Jhansi',
    slug: 'insurance-advisor-jobs-jhansi-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Jhansi, Babina, Moth, and Garautha',
    localFlavor: 'the gateway to Bundelkhand and a major military and commercial center in southern UP',
  },
  {
    city: 'Kannauj',
    slug: 'insurance-advisor-jobs-kannauj-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Kannauj, Chhibramau, Tirwa, and Saurikh',
    localFlavor: 'the perfume capital of India famous for its traditional attar and fragrance industry',
  },
  {
    city: 'Kanpur Dehat',
    slug: 'insurance-advisor-jobs-kanpur-dehat-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Kanpur Dehat, Akbarpur, Derapur, and Rasulabad',
    localFlavor: 'a rural district adjoining Kanpur city with strong agricultural and small industry sectors',
  },
  {
    city: 'Kasganj',
    slug: 'insurance-advisor-jobs-kasganj-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Kasganj, Patiyali, Soron, and Sahawar',
    localFlavor: 'a culturally diverse district in western UP with active grain and textile trading',
  },
  {
    city: 'Kaushambi',
    slug: 'insurance-advisor-jobs-kaushambi-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Kaushambi, Manjhanpur, Sirathu, and Chail',
    localFlavor: 'an ancient Buddhist site near Prayagraj with developing rural economy and infrastructure',
  },
  {
    city: 'Kushinagar',
    slug: 'insurance-advisor-jobs-kushinagar-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Kushinagar, Padrauna, Kasia, and Hata',
    localFlavor: 'a globally significant Buddhist pilgrimage destination with a new international airport',
  },
  {
    city: 'Lakhimpur Kheri',
    slug: 'insurance-advisor-jobs-lakhimpur-kheri-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Lakhimpur, Gola, Nighasan, and Palia Kalan',
    localFlavor: 'the largest district in UP by area with major sugar mills and agricultural output',
  },
  {
    city: 'Lalitpur',
    slug: 'insurance-advisor-jobs-lalitpur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Lalitpur, Talbehat, Mehrauni, and Madawara',
    localFlavor: 'a southern Bundelkhand district with mineral resources and growing connectivity',
  },
  {
    city: 'Maharajganj',
    slug: 'insurance-advisor-jobs-maharajganj-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Maharajganj, Nichlaul, Pharenda, and Siswa Bazar',
    localFlavor: 'a Nepal-border district in northeastern UP with expanding trade and sugar industry',
  },
  {
    city: 'Mahoba',
    slug: 'insurance-advisor-jobs-mahoba-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Mahoba, Kulpahar, Charkhari, and Kabrai',
    localFlavor: 'a historic Chandela-era district in Bundelkhand known for its ancient temples and lakes',
  },
  {
    city: 'Mainpuri',
    slug: 'insurance-advisor-jobs-mainpuri-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Mainpuri, Bhogaon, Kishni, and Karhal',
    localFlavor: 'an agriculturally productive district in the Doab region of central UP',
  },
  {
    city: 'Mathura',
    slug: 'insurance-advisor-jobs-mathura-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Mathura, Vrindavan, Baldeo, and Govardhan',
    localFlavor: 'the birthplace of Lord Krishna and a major pilgrimage and tourism center in western UP',
  },
  {
    city: 'Mau',
    slug: 'insurance-advisor-jobs-mau-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Mau, Ghosi, Muhammadabad, and Kopaganj',
    localFlavor: 'a prominent textile and power-loom hub in eastern Uttar Pradesh',
  },
  {
    city: 'Mirzapur',
    slug: 'insurance-advisor-jobs-mirzapur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Mirzapur, Chunar, Lalganj, and Marihan',
    localFlavor: 'a Ganges-side city known for its carpet industry and Vindhyachal pilgrimage',
  },
  {
    city: 'Moradabad',
    slug: 'insurance-advisor-jobs-moradabad-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Moradabad, Sambhal, Thakurdwara, and Bilari',
    localFlavor: 'the Brass City of India and a leading export hub for handicrafts and metalware',
  },
  {
    city: 'Muzaffarnagar',
    slug: 'insurance-advisor-jobs-muzaffarnagar-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Muzaffarnagar, Jansath, Khatauli, and Budhana',
    localFlavor: 'a major sugarcane-producing district in western UP with strong jaggery and paper industries',
  },
  {
    city: 'Pilibhit',
    slug: 'insurance-advisor-jobs-pilibhit-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Pilibhit, Bisalpur, Puranpur, and Barkhera',
    localFlavor: 'a terai district known for its tiger reserve and thriving sugarcane farming',
  },
  {
    city: 'Pratapgarh',
    slug: 'insurance-advisor-jobs-pratapgarh-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Pratapgarh, Kunda, Patti, and Lalganj',
    localFlavor: 'a culturally rich district between Prayagraj and Lucknow with strong agricultural base',
  },
  {
    city: 'Raebareli',
    slug: 'insurance-advisor-jobs-raebareli-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Raebareli, Lalganj, Salon, and Dalmau',
    localFlavor: 'a politically prominent district near Lucknow with a major railway coach factory',
  },
  {
    city: 'Rampur',
    slug: 'insurance-advisor-jobs-rampur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Rampur, Bilaspur, Shahabad, and Swar',
    localFlavor: 'a Rohilkhand district known for its Rampuri knife craft and rich Nawabi heritage',
  },
  {
    city: 'Saharanpur',
    slug: 'insurance-advisor-jobs-saharanpur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Saharanpur, Deoband, Behat, and Nakur',
    localFlavor: 'a major wood carving and paper industry center in northwestern Uttar Pradesh',
  },
  {
    city: 'Sambhal',
    slug: 'insurance-advisor-jobs-sambhal-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Sambhal, Chandausi, Babrala, and Gunnaur',
    localFlavor: 'a historically significant district with growing horn and bone handicraft industries',
  },
  {
    city: 'Sant Kabir Nagar',
    slug: 'insurance-advisor-jobs-sant-kabir-nagar-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Sant Kabir Nagar, Khalilabad, Maghar, and Mehdawal',
    localFlavor: 'a spiritually important district in eastern UP named after the revered poet-saint Kabir',
  },
  {
    city: 'Shahjahanpur',
    slug: 'insurance-advisor-jobs-shahjahanpur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Shahjahanpur, Tilhar, Powayan, and Jalalabad',
    localFlavor: 'a freedom-movement landmark and major agricultural trade center in Rohilkhand',
  },
  {
    city: 'Shamli',
    slug: 'insurance-advisor-jobs-shamli-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Shamli, Kairana, Thanabhawan, and Un',
    localFlavor: 'a compact western UP district near Delhi NCR with active sugarcane and grain markets',
  },
  {
    city: 'Shrawasti',
    slug: 'insurance-advisor-jobs-shrawasti-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Shrawasti, Bhinga, Ikauna, and Jamunaha',
    localFlavor: 'an ancient Buddhist pilgrimage site and Nepal-border district with developing economy',
  },
  {
    city: 'Siddharthnagar',
    slug: 'insurance-advisor-jobs-siddharthnagar-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Siddharthnagar, Naugarh, Bansi, and Domariyaganj',
    localFlavor: 'a Nepal-border district named in honour of Lord Buddha with growing rural commerce',
  },
  {
    city: 'Sitapur',
    slug: 'insurance-advisor-jobs-sitapur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Sitapur, Misrikh, Biswan, and Laharpur',
    localFlavor: 'a large Awadhi district with an eye hospital of national repute and active trade markets',
  },
  {
    city: 'Sonbhadra',
    slug: 'insurance-advisor-jobs-sonbhadra-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Sonbhadra, Robertsganj, Obra, and Renukoot',
    localFlavor: 'the energy capital of UP with major thermal power plants and mineral resources',
  },
  {
    city: 'Sultanpur',
    slug: 'insurance-advisor-jobs-sultanpur-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Sultanpur, Kadipur, Musafirkhana, and Dostpur',
    localFlavor: 'an ancient Awadhi district with deep cultural roots and expanding commercial activities',
  },
  {
    city: 'Unnao',
    slug: 'insurance-advisor-jobs-unnao-uttar-pradesh',
    state: 'Uttar Pradesh',
    nearbyAreas: 'Unnao, Shuklaganj, Hasanganj, and Purwa',
    localFlavor: 'a major leather and tannery industry center strategically located between Lucknow and Kanpur',
  },

  // ── West Bengal ──
  {
    city: 'Kolkata',
    slug: 'insurance-advisor-jobs-kolkata',
    state: 'West Bengal',
    nearbyAreas: 'Kolkata, Salt Lake, Rajarhat, and Barasat',
    localFlavor: 'the cultural and commercial capital of eastern India',
  },
  {
    city: 'Howrah',
    slug: 'insurance-advisor-jobs-howrah',
    state: 'West Bengal',
    nearbyAreas: 'Howrah, Shibpur, Liluah, and Uluberia',
    localFlavor: 'a major industrial and transportation hub across the Hooghly from Kolkata',
  },
  {
    city: 'Durgapur',
    slug: 'insurance-advisor-jobs-durgapur',
    state: 'West Bengal',
    nearbyAreas: 'Durgapur, Andal, Kanksa, and Galsi',
    localFlavor: 'a leading industrial city and steel hub in western West Bengal',
  },
  {
    city: 'Asansol',
    slug: 'insurance-advisor-jobs-asansol',
    state: 'West Bengal',
    nearbyAreas: 'Asansol, Burnpur, Kulti, and Jamuria',
    localFlavor: 'the second-largest city in West Bengal and a key mining and industrial center',
  },
  {
    city: 'Siliguri',
    slug: 'insurance-advisor-jobs-siliguri',
    state: 'West Bengal',
    nearbyAreas: 'Siliguri, Jalpaiguri, New Jalpaiguri, and Bagdogra',
    localFlavor: 'a strategic gateway to northeast India and the Darjeeling hills',
  },
  {
    city: 'Kharagpur',
    slug: 'insurance-advisor-jobs-kharagpur',
    state: 'West Bengal',
    nearbyAreas: 'Kharagpur, Midnapore, Hijli, and Debra',
    localFlavor: 'a prominent railway and educational city in West Midnapore',
  },
  {
    city: 'Haldia',
    slug: 'insurance-advisor-jobs-haldia',
    state: 'West Bengal',
    nearbyAreas: 'Haldia, Tamluk, Sutahata, and Kolaghat',
    localFlavor: 'a major port and petrochemical industrial hub in East Midnapore',
  },
  {
    city: 'Bardhaman',
    slug: 'insurance-advisor-jobs-bardhaman',
    state: 'West Bengal',
    nearbyAreas: 'Bardhaman, Memari, Kalna, and Jamalpur',
    localFlavor: 'a historic city and district headquarters known for agriculture and education',
  },
  {
    city: 'Malda',
    slug: 'insurance-advisor-jobs-malda',
    state: 'West Bengal',
    nearbyAreas: 'Malda, English Bazar, Old Malda, and Gazole',
    localFlavor: 'a culturally rich district in northern West Bengal famous for its mango trade',
  },
  {
    city: 'Berhampore',
    slug: 'insurance-advisor-jobs-berhampore',
    state: 'West Bengal',
    nearbyAreas: 'Berhampore, Murshidabad, Jiaganj, and Lalbag',
    localFlavor: 'the district headquarters of Murshidabad with deep historical significance',
  },
  {
    city: 'Krishnanagar',
    slug: 'insurance-advisor-jobs-krishnanagar',
    state: 'West Bengal',
    nearbyAreas: 'Krishnanagar, Nabadwip, Shantipur, and Ranaghat',
    localFlavor: 'a vibrant city in Nadia district known for its clay art and cultural heritage',
  },
  {
    city: 'Raniganj',
    slug: 'insurance-advisor-jobs-raniganj',
    state: 'West Bengal',
    nearbyAreas: 'Raniganj, Andal, Dubrajpur, and Ondal',
    localFlavor: 'a key coal belt town in western West Bengal with growing commercial opportunities',
  },

  // ── Madhya Pradesh ──
  {
    city: 'Indore',
    slug: 'insurance-advisor-jobs-indore',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Indore, Dewas, Mhow, and Pithampur',
    localFlavor: 'the commercial capital of Madhya Pradesh and a thriving business hub',
  },
  {
    city: 'Bhopal',
    slug: 'insurance-advisor-jobs-bhopal',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Bhopal, Hoshangabad, Sehore, and Raisen',
    localFlavor: 'the capital city of Madhya Pradesh known for its lakes and administrative importance',
  },
  {
    city: 'Jabalpur',
    slug: 'insurance-advisor-jobs-jabalpur',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Jabalpur, Katni, Mandla, and Narsinghpur',
    localFlavor: 'a major educational and judicial center in central Madhya Pradesh',
  },
  {
    city: 'Gwalior',
    slug: 'insurance-advisor-jobs-gwalior',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Gwalior, Morena, Datia, and Shivpuri',
    localFlavor: 'a historically significant city in northern Madhya Pradesh with a vibrant economy',
  },
  {
    city: 'Ujjain',
    slug: 'insurance-advisor-jobs-ujjain',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Ujjain, Nagda, Agar Malwa, and Tarana',
    localFlavor: 'one of the holiest cities in India and a growing commercial center in western MP',
  },
  {
    city: 'Ratlam',
    slug: 'insurance-advisor-jobs-ratlam',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Ratlam, Jaora, Alot, and Sailana',
    localFlavor: 'a key railway junction and trading town in western Madhya Pradesh',
  },
  {
    city: 'Sagar',
    slug: 'insurance-advisor-jobs-sagar',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Sagar, Damoh, Khurai, and Banda',
    localFlavor: 'a major educational hub in the Bundelkhand region of Madhya Pradesh',
  },
  {
    city: 'Satna',
    slug: 'insurance-advisor-jobs-satna',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Satna, Maihar, Chitrakoot, and Amarpatan',
    localFlavor: 'a prominent cement and mining industrial center in eastern Madhya Pradesh',
  },
  {
    city: 'Rewa',
    slug: 'insurance-advisor-jobs-rewa',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Rewa, Mauganj, Sirmour, and Hanumana',
    localFlavor: 'the divisional headquarters of the Vindhya region with growing commercial activity',
  },
  {
    city: 'Katni',
    slug: 'insurance-advisor-jobs-katni',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Katni, Vijayraghavgarh, Bahoriband, and Rithi',
    localFlavor: 'a major railway junction and limestone mining center in Madhya Pradesh',
  },
  {
    city: 'Dewas',
    slug: 'insurance-advisor-jobs-dewas',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Dewas, Sonkatch, Bagli, and Kannod',
    localFlavor: 'a key industrial city near Indore known for its manufacturing sector',
  },
  {
    city: 'Khandwa',
    slug: 'insurance-advisor-jobs-khandwa',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Khandwa, Burhanpur, Harda, and Nepanagar',
    localFlavor: 'a strategically located trade and transport hub in the Nimar region of MP',
  },
  {
    city: 'Chhindwara',
    slug: 'insurance-advisor-jobs-chhindwara',
    state: 'Madhya Pradesh',
    nearbyAreas: 'Chhindwara, Pandhurna, Sausar, and Amarwara',
    localFlavor: 'a scenic hill district with a growing economy in southern Madhya Pradesh',
  },

  // ── Bihar ──
  {
    city: 'Patna',
    slug: 'insurance-advisor-jobs-patna',
    state: 'Bihar',
    nearbyAreas: 'Patna, Danapur, Phulwari Sharif, and Bakhtiarpur',
    localFlavor: 'the capital city of Bihar and a major administrative and commercial hub',
  },
  {
    city: 'Gaya',
    slug: 'insurance-advisor-jobs-gaya',
    state: 'Bihar',
    nearbyAreas: 'Gaya, Bodh Gaya, Sherghati, and Tekari',
    localFlavor: 'a historically and religiously significant city attracting visitors from around the world',
  },
  {
    city: 'Muzaffarpur',
    slug: 'insurance-advisor-jobs-muzaffarpur',
    state: 'Bihar',
    nearbyAreas: 'Muzaffarpur, Hajipur, Vaishali, and Sitamarhi',
    localFlavor: 'a major trade and educational center in north Bihar known for its litchi production',
  },
  {
    city: 'Bhagalpur',
    slug: 'insurance-advisor-jobs-bhagalpur',
    state: 'Bihar',
    nearbyAreas: 'Bhagalpur, Naugachhia, Kahalgaon, and Sultanganj',
    localFlavor: 'the Silk City of India and a key commercial center in eastern Bihar',
  },
  {
    city: 'Darbhanga',
    slug: 'insurance-advisor-jobs-darbhanga',
    state: 'Bihar',
    nearbyAreas: 'Darbhanga, Laheriasarai, Madhubani, and Samastipur',
    localFlavor: 'a culturally rich city and the heart of the Mithila region',
  },
  {
    city: 'Purnia',
    slug: 'insurance-advisor-jobs-purnia',
    state: 'Bihar',
    nearbyAreas: 'Purnia, Katihar, Araria, and Kishanganj',
    localFlavor: 'a fast-growing divisional headquarters in northeastern Bihar',
  },
  {
    city: 'Arrah',
    slug: 'insurance-advisor-jobs-arrah',
    state: 'Bihar',
    nearbyAreas: 'Arrah, Buxar, Bihiya, and Jagdishpur',
    localFlavor: 'the district headquarters of Bhojpur with a rich historical legacy',
  },
  {
    city: 'Begusarai',
    slug: 'insurance-advisor-jobs-begusarai',
    state: 'Bihar',
    nearbyAreas: 'Begusarai, Barauni, Teghra, and Bakhri',
    localFlavor: 'an industrial district known for its refinery and growing commercial activity',
  },
  {
    city: 'Katihar',
    slug: 'insurance-advisor-jobs-katihar',
    state: 'Bihar',
    nearbyAreas: 'Katihar, Manihari, Barari, and Korha',
    localFlavor: 'a major railway junction and trade center in eastern Bihar',
  },
  {
    city: 'Munger',
    slug: 'insurance-advisor-jobs-munger',
    state: 'Bihar',
    nearbyAreas: 'Munger, Jamalpur, Kharagpur, and Tarapur',
    localFlavor: 'a historic city on the banks of the Ganges known for its yoga and industrial heritage',
  },
  {
    city: 'Chapra',
    slug: 'insurance-advisor-jobs-chapra',
    state: 'Bihar',
    nearbyAreas: 'Chapra, Revelganj, Dighwara, and Marhaura',
    localFlavor: 'the district headquarters of Saran and a prominent town in north-central Bihar',
  },
  {
    city: 'Hajipur',
    slug: 'insurance-advisor-jobs-hajipur',
    state: 'Bihar',
    nearbyAreas: 'Hajipur, Vaishali, Mahua, and Lalganj',
    localFlavor: 'the headquarters of Vaishali district and a rapidly developing city near Patna',
  },
  {
    city: 'Sitamarhi',
    slug: 'insurance-advisor-jobs-sitamarhi',
    state: 'Bihar',
    nearbyAreas: 'Sitamarhi, Pupri, Dumra, and Riga',
    localFlavor: 'a spiritually significant town near the Nepal border with growing local commerce',
  },
  {
    city: 'Samastipur',
    slug: 'insurance-advisor-jobs-samastipur',
    state: 'Bihar',
    nearbyAreas: 'Samastipur, Rosera, Dalsinghsarai, and Patori',
    localFlavor: 'a key agricultural district and railway hub in central Bihar',
  },
  {
    city: 'Motihari',
    slug: 'insurance-advisor-jobs-motihari',
    state: 'Bihar',
    nearbyAreas: 'Motihari, Bettiah, Raxaul, and Adapur',
    localFlavor: 'the district headquarters of East Champaran with historical importance in the freedom movement',
  },
  {
    city: 'Bettiah',
    slug: 'insurance-advisor-jobs-bettiah',
    state: 'Bihar',
    nearbyAreas: 'Bettiah, Narkatiaganj, Bagaha, and Chanpatia',
    localFlavor: 'the headquarters of West Champaran and a growing town in northwestern Bihar',
  },
];
