
ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS article_images JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS internal_links JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS word_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS faq_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS has_faq_schema BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS schema_json TEXT,
  ADD COLUMN IF NOT EXISTS status VARCHAR DEFAULT 'draft',
  ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS language VARCHAR DEFAULT 'hi';
